lol_df_creation.ipynb is a data pre-processing aimed jupyter notebook
it's main objective is generating a database from which a prediction model
can be obtained and recurring patterns can be observed
Copyright (C) Keshava Tonathiu Sanchez Barbosa (keshava.t.s.b@gmail.com)

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

In [1]:
import pandas as pd

In [57]:
base_df = pd.read_csv("2020_LoL_esports_match_data_from_OraclesElixir_20201016.csv")

In [58]:
base_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 69708 entries, 0 to 69707
Columns: 105 entries, gameid to csdiffat15
dtypes: float64(69), int64(20), object(16)
memory usage: 55.8+ MB

In [59]:
base_df.head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
0,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,23.0,4888.0,7368.0,131.0,4723.0,7202.0,118.0,165.0,166.0,13.0
1,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,-10.0,4385.0,4817.0,91.0,4784.0,4667.0,98.0,-399.0,150.0,-7.0
2,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,-9.0,4809.0,6275.0,129.0,5218.0,8112.0,140.0,-409.0,-1837.0,-11.0
3,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,3.0,4915.0,4959.0,136.0,4864.0,5360.0,135.0,51.0,-401.0,1.0
4,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,1.0,2956.0,3800.0,20.0,3189.0,3543.0,28.0,-233.0,257.0,-8.0

In [60]:
base_df.describe()

,year,playoffs,game,patch,playerid,gamelength,result,kills,deaths,assists,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
count,69708.000000,69708.000000,69708.000000,69708.00000,69708.000000,69708.000000,69708.000000,69708.000000,69708.000000,69708.000000,...,69144.000000,69096.000000,69096.000000,69096.000000,69096.000000,69096.000000,69096.000000,69096.00000,69096.000000,69096.000000
mean,2020.001377,0.130487,1.562920,10.09911,29.583333,1954.651059,0.500000,4.394589,4.402393,10.117634,...,0.000000,8174.707277,9662.981330,166.417231,8174.707277,9662.981330,166.417231,0.00000,0.000000,0.000000
std,0.037085,0.336841,0.846582,0.05996,57.650881,346.490541,0.500004,5.415668,5.189552,12.173697,...,18.340052,7401.524015,8761.291401,155.088366,7401.524015,8761.291401,155.088366,1480.76203,1136.236597,27.561916
min,2020.000000,0.000000,1.000000,9.24000,1.000000,1005.000000,0.000000,0.000000,0.000000,0.000000,...,-104.000000,2562.000000,2501.000000,0.000000,2562.000000,2501.000000,0.000000,-11913.00000,-9240.000000,-165.000000
25%,2020.000000,0.000000,1.000000,10.06000,3.750000,1712.000000,0.000000,1.000000,1.000000,3.000000,...,-8.000000,4558.000000,4902.000000,89.000000,4558.000000,4902.000000,89.000000,-658.00000,-566.000000,-13.000000
50%,2020.000000,0.000000,1.000000,10.12000,6.500000,1914.000000,0.500000,3.000000,3.000000,6.000000,...,0.000000,5206.000000,6284.000000,123.000000,5206.000000,6284.000000,123.000000,0.00000,0.000000,0.000000
75%,2020.000000,0.000000,2.000000,10.14000,9.250000,2157.000000,1.000000,6.000000,5.000000,11.000000,...,8.000000,6042.000000,7659.000000,146.000000,6042.000000,7659.000000,146.000000,658.00000,566.000000,13.000000
max,2021.000000,1.000000,5.000000,10.20000,200.000000,3751.000000,1.000000,53.000000,53.000000,108.000000,...,104.000000,34110.000000,35266.000000,614.000000,34110.000000,35266.000000,614.000000,11913.00000,9240.000000,165.000000

In [61]:
nombres_columnas = base_df.columns
#for i in range(len(nombres_columnas)):
    #print(nombres_columnas[i])

In [62]:
team_stats = []
player_stats = []
for i in range(len(base_df)):
    if base_df.iloc[i]["position"] == "team":
        team_stats.append(base_df.iloc[i])
    else:
        player_stats.append(base_df.iloc[i])

In [63]:
team_stats_df = pd.DataFrame(team_stats)
player_stats_df = pd.DataFrame(player_stats)

In [64]:
team_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11618 entries, 10 to 69707
Columns: 105 entries, gameid to csdiffat15
dtypes: float64(71), int64(20), object(14)
memory usage: 9.4+ MB

In [65]:
player_stats_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 58090 entries, 0 to 69705
Columns: 105 entries, gameid to csdiffat15
dtypes: float64(69), int64(20), object(16)
memory usage: 47.0+ MB

### Notas

##### posibles atributos que se pueden descartar:
- url
- year
- split
- playoffs
- game
- team
- champion
- bans 1-5

In [11]:
team_stats_df.isna().sum()

gameid                8
datacompleteness      0
url                   0
league                0
year                  0
                   ...
opp_xpat15          102
opp_csat15          102
golddiffat15        102
xpdiffat15          102
csdiffat15          102
Length: 105, dtype: int64

In [12]:
player_stats_df.isna().sum()

gameid               40
datacompleteness      0
url                   0
league                0
year                  0
                   ...
opp_xpat15          510
opp_csat15          510
golddiffat15        510
xpdiffat15          510
csdiffat15          510
Length: 105, dtype: int64

In [67]:
team_stats_df[team_stats_df["datacompleteness"] == 'complete']

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
10,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0
11,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,-8.0,22778.0,28884.0,519.0,21953.0,27219.0,507.0,825.0,1665.0,12.0
22,ESPORTSTMNT03/1241322,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 09:00:58,2,9.24,...,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0
23,ESPORTSTMNT03/1241322,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 09:00:58,2,9.24,...,34.0,27198.0,31702.0,557.0,21714.0,26869.0,501.0,5484.0,4833.0,56.0
34,ESPORTSTMNT03/1241324,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 10:05:17,3,9.24,...,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69683,ESPORTSTMNT03/1552288,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 08:52:43,1,10.19,...,-17.0,23735.0,29784.0,560.0,24289.0,30410.0,573.0,-554.0,-626.0,-13.0
69694,ESPORTSTMNT03/1552298,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 10:54:35,2,10.19,...,-26.0,24244.0,28529.0,518.0,25125.0,29449.0,547.0,-881.0,-920.0,-29.0
69695,ESPORTSTMNT03/1552298,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 10:54:35,2,10.19,...,26.0,25125.0,29449.0,547.0,24244.0,28529.0,518.0,881.0,920.0,29.0
69706,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,-3.0,25045.0,30259.0,528.0,23970.0,29715.0,543.0,1075.0,544.0,-15.0
69707,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,3.0,23970.0,29715.0,543.0,25045.0,30259.0,528.0,-1075.0,-544.0,15.0

In [69]:
player_stats_df[player_stats_df["datacompleteness"] == 'complete']

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
0,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,23.0,4888.0,7368.0,131.0,4723.0,7202.0,118.0,165.0,166.0,13.0
1,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,-10.0,4385.0,4817.0,91.0,4784.0,4667.0,98.0,-399.0,150.0,-7.0
2,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,-9.0,4809.0,6275.0,129.0,5218.0,8112.0,140.0,-409.0,-1837.0,-11.0
3,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,3.0,4915.0,4959.0,136.0,4864.0,5360.0,135.0,51.0,-401.0,1.0
4,ESPORTSTMNT03/1241318,complete,http://matchhistory.na.leagueoflegends.com/en/...,KeSPA,2020,NaN,0,2020-01-03 07:33:26,1,9.24,...,1.0,2956.0,3800.0,20.0,3189.0,3543.0,28.0,-233.0,257.0,-8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69701,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,4.0,5114.0,7341.0,128.0,6012.0,8424.0,135.0,-898.0,-1083.0,-7.0
69702,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,5.0,4938.0,5778.0,104.0,5396.0,5445.0,94.0,-458.0,333.0,10.0
69703,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,-10.0,5451.0,7863.0,154.0,5681.0,8425.0,165.0,-230.0,-562.0,-11.0
69704,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,5.0,5243.0,5635.0,138.0,4639.0,4932.0,114.0,604.0,703.0,24.0
69705,ESPORTSTMNT03/1552301,complete,http://matchhistory.na.leagueoflegends.com/en/...,WCS,2020,NaN,0,2020-10-15 11:55:38,3,10.19,...,-1.0,3224.0,3098.0,19.0,3317.0,3033.0,20.0,-93.0,65.0,-1.0

##### nota: en el dataframe, en result, el equipo asignado con "1" gano y el equipo con "0" perdio
##### nota: todas las columnas con el prefijo opp_ indican que son las estadisticas del oponente, muy probable se eliminen por la condensacion de informacion 
##### nota: gamelength esta con el siguiente formato mm:ss, sin embargo en la informacion del df se encuentra sin los ":" por ejemplo 22:00 = 2200

### eliminando datos faltantes

In [70]:
team_stats_df_no_na = team_stats_df[team_stats_df["datacompleteness"] == 'complete']

In [71]:
len(team_stats_df_no_na), len(team_stats_df)

(11460, 11618)

In [72]:
player_stats_df_no_na = player_stats_df[player_stats_df['datacompleteness'] == 'complete']

In [73]:
len(player_stats_df_no_na), len(player_stats_df)

(57300, 58090)

##### Lista de columnas a eliminar, todas estas columnas son eliminaciones "obvias" es decir se pueden categorizar como: irrelevantes para el estudio, su informacion no esta contenida en el dataframe individual de jugadores/equipos, su informacion es redundante

###### esta lista puede expandirse aun mas conforme se vaya trabajando

- url
- league
- year
- split
- playoffs
- date
- game
- patch
- playerid
- player
- team
- champion
- bans

jugadores:
- dragons (type unkown)
- firstblood
- firstbloodassist
- firstbloodvictim
- team kpm
- ckpm
- firstdragon
- dragon
- opp_dragons
- elementaldrakes
- opp_elementaldrakes
- infernals
- mountains
- clouds
- oceans
- elders
- opp_elders
- firstherald
- heralds
- opp_heralds
- firstbaron
- barons
- opp_barons
- firsttower
- towers
- opp_towers
- firstmidtower
- firsttothreetowers
- inhibitors
- opp_inhibitors
- gspd

equipo:
- position
- firstbloodkill
- firstbloodassist
- firstbloodvictim
- damageshare
- earnedgoldshare
- total cs
- dragons (type unknown)

In [74]:
general_remove = ["datacompleteness", "url", "league", "year", "split", "playoffs", "date", "game", "patch", "playerid", "player", "team", "champion", "ban1", "ban2", "ban3", "ban4", "ban5"]

In [75]:
players_remove = ["dragons (type unknown)", "firstblood", "firstbloodassist", "firstbloodvictim", "team kpm", "ckpm", "firstdragon", "dragons", "opp_dragons", "elementaldrakes", "opp_elementaldrakes", "infernals", "oceans", "mountains", "clouds", "elders", "opp_elders", "firstherald", "heralds", "opp_heralds", "firstbaron", "barons", "opp_barons", "firsttower", "towers", "opp_towers", "firstmidtower", "firsttothreetowers", "inhibitors", "opp_inhibitors", "gspd"]

In [76]:
teams_remove = ["position", "firstbloodkill", "firstbloodassist", "firstbloodvictim", "damageshare", "earnedgoldshare", "total cs", "dragons (type unknown)"]

In [77]:
for i in general_remove:
    team_stats_df_no_na.drop(i, inplace = True, axis = 1)
    player_stats_df_no_na.drop(i, inplace = True, axis = 1)
    
team_stats_df_no_na.info()

C:\Users\kesha\anaconda3\envs\ml\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11460 entries, 10 to 69707
Data columns (total 87 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    11452 non-null  object
 1   side                      11460 non-null  object
 2   position                  11460 non-null  object
 3   gamelength                11460 non-null  int64
 4   result                    11460 non-null  int64
 5   kills                     11460 non-null  int64
 6   deaths                    11460 non-null  int64
 7   assists                   11460 non-null  int64
 8   teamkills                 11460 non-null  int64
 9   teamdeaths                11460 non-null  int64
 10  doublekills               11460 non-null  float64
 11  triplekills               11460 non-null  float64
 12  quadrakills               11460 non-null  float64
 13  pentakills                11460 non-null  float64
 14  firstblood                11460 non-null  float64
 15  firstbloodkill            0 non-null      float64
 16  firstbloodassist          0 non-null      float64
 17  firstbloodvictim          0 non-null      float64
 18  team kpm                  11460 non-null  float64
 19  ckpm                      11460 non-null  float64
 20  firstdragon               11458 non-null  float64
 21  dragons                   11460 non-null  float64
 22  opp_dragons               11460 non-null  float64
 23  elementaldrakes           11460 non-null  float64
 24  opp_elementaldrakes       11460 non-null  float64
 25  infernals                 11460 non-null  float64
 26  mountains                 11460 non-null  float64
 27  clouds                    11460 non-null  float64
 28  oceans                    11460 non-null  float64
 29  dragons (type unknown)    0 non-null      float64
 30  elders                    11460 non-null  float64
 31  opp_elders                11460 non-null  float64
 32  firstherald               11460 non-null  float64
 33  heralds                   11460 non-null  float64
 34  opp_heralds               11460 non-null  float64
 35  firstbaron                11168 non-null  float64
 36  barons                    11460 non-null  float64
 37  opp_barons                11460 non-null  float64
 38  firsttower                11460 non-null  float64
 39  towers                    11460 non-null  float64
 40  opp_towers                11460 non-null  float64
 41  firstmidtower             11460 non-null  float64
 42  firsttothreetowers        11460 non-null  float64
 43  inhibitors                11460 non-null  float64
 44  opp_inhibitors            11460 non-null  float64
 45  damagetochampions         11460 non-null  int64
 46  dpm                       11460 non-null  float64
 47  damageshare               0 non-null      float64
 48  damagetakenperminute      11460 non-null  float64
 49  damagemitigatedperminute  11460 non-null  float64
 50  wardsplaced               11460 non-null  int64
 51  wpm                       11460 non-null  float64
 52  wardskilled               11460 non-null  int64
 53  wcpm                      11460 non-null  float64
 54  controlwardsbought        11460 non-null  int64
 55  visionscore               11460 non-null  float64
 56  vspm                      11460 non-null  float64
 57  totalgold                 11460 non-null  int64
 58  earnedgold                11460 non-null  int64
 59  earned gpm                11460 non-null  float64
 60  earnedgoldshare           0 non-null      float64
 61  goldspent                 11460 non-null  float64
 62  gspd                      11460 non-null  float64
 63  total cs                  0 non-null      float64
 64  minionkills               8188 non-null   float64
 65  monsterkills              11460 non-null  int64
 66  monsterkillsownjungle     11460 non-null  int64
 67  monsterkillsenemyjungle   11460 non-null  int64
 68  cspm                      8188 non-null   float64
 69  goldat10                  11460 non-null  float64
 70  xpat10                    11460 non-null  float64
 71  csat10                    11460 non-null  float64
 72  opp_goldat10              11460 non-null  float64
 73  opp_xpat10                11460 non-null  float64
 74  opp_csat10                11460 non-null  float64
 75  golddiffat10              11460 non-null  float64
 76  xpdiffat10                11460 non-null  float64
 77  csdiffat10                11460 non-null  float64
 78  goldat15                  11460 non-null  float64
 79  xpat15                    11460 non-null  float64
 80  csat15                    11460 non-null  float64
 81  opp_goldat15              11460 non-null  float64
 82  opp_xpat15                11460 non-null  float64
 83  opp_csat15                11460 non-null  float64
 84  golddiffat15              11460 non-null  float64
 85  xpdiffat15                11460 non-null  float64
 86  csdiffat15                11460 non-null  float64
dtypes: float64(68), int64(16), object(3)
memory usage: 7.7+ MB

In [78]:
for i in players_remove:
    player_stats_df_no_na.drop(i, inplace = True, axis = 1)
    
player_stats_df_no_na

,gameid,side,position,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
0,ESPORTSTMNT03/1241318,Blue,top,2220,1,0,3,7,17,11,...,23.0,4888.0,7368.0,131.0,4723.0,7202.0,118.0,165.0,166.0,13.0
1,ESPORTSTMNT03/1241318,Blue,jng,2220,1,4,0,9,17,11,...,-10.0,4385.0,4817.0,91.0,4784.0,4667.0,98.0,-399.0,150.0,-7.0
2,ESPORTSTMNT03/1241318,Blue,mid,2220,1,5,2,5,17,11,...,-9.0,4809.0,6275.0,129.0,5218.0,8112.0,140.0,-409.0,-1837.0,-11.0
3,ESPORTSTMNT03/1241318,Blue,bot,2220,1,7,1,9,17,11,...,3.0,4915.0,4959.0,136.0,4864.0,5360.0,135.0,51.0,-401.0,1.0
4,ESPORTSTMNT03/1241318,Blue,sup,2220,1,1,5,3,17,11,...,1.0,2956.0,3800.0,20.0,3189.0,3543.0,28.0,-233.0,257.0,-8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69701,ESPORTSTMNT03/1552301,Red,top,1548,1,2,2,10,21,7,...,4.0,5114.0,7341.0,128.0,6012.0,8424.0,135.0,-898.0,-1083.0,-7.0
69702,ESPORTSTMNT03/1552301,Red,jng,1548,1,7,0,6,21,7,...,5.0,4938.0,5778.0,104.0,5396.0,5445.0,94.0,-458.0,333.0,10.0
69703,ESPORTSTMNT03/1552301,Red,mid,1548,1,5,0,8,21,7,...,-10.0,5451.0,7863.0,154.0,5681.0,8425.0,165.0,-230.0,-562.0,-11.0
69704,ESPORTSTMNT03/1552301,Red,bot,1548,1,3,1,6,21,7,...,5.0,5243.0,5635.0,138.0,4639.0,4932.0,114.0,604.0,703.0,24.0
69705,ESPORTSTMNT03/1552301,Red,sup,1548,1,4,4,4,21,7,...,-1.0,3224.0,3098.0,19.0,3317.0,3033.0,20.0,-93.0,65.0,-1.0

In [79]:
player_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57300 entries, 0 to 69705
Data columns (total 56 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    57260 non-null  object
 1   side                      57300 non-null  object
 2   position                  57300 non-null  object
 3   gamelength                57300 non-null  int64
 4   result                    57300 non-null  int64
 5   kills                     57300 non-null  int64
 6   deaths                    57300 non-null  int64
 7   assists                   57300 non-null  int64
 8   teamkills                 57300 non-null  int64
 9   teamdeaths                57300 non-null  int64
 10  doublekills               57300 non-null  float64
 11  triplekills               57300 non-null  float64
 12  quadrakills               57300 non-null  float64
 13  pentakills                57300 non-null  float64
 14  firstbloodkill            57300 non-null  float64
 15  damagetochampions         57300 non-null  int64
 16  dpm                       57300 non-null  float64
 17  damageshare               57300 non-null  float64
 18  damagetakenperminute      57300 non-null  float64
 19  damagemitigatedperminute  57300 non-null  float64
 20  wardsplaced               57300 non-null  int64
 21  wpm                       57300 non-null  float64
 22  wardskilled               57300 non-null  int64
 23  wcpm                      57300 non-null  float64
 24  controlwardsbought        57300 non-null  int64
 25  visionscore               57300 non-null  float64
 26  vspm                      57300 non-null  float64
 27  totalgold                 57300 non-null  int64
 28  earnedgold                57300 non-null  int64
 29  earned gpm                57300 non-null  float64
 30  earnedgoldshare           57300 non-null  float64
 31  goldspent                 57300 non-null  float64
 32  total cs                  57300 non-null  float64
 33  minionkills               57300 non-null  float64
 34  monsterkills              57300 non-null  int64
 35  monsterkillsownjungle     57300 non-null  int64
 36  monsterkillsenemyjungle   57300 non-null  int64
 37  cspm                      57300 non-null  float64
 38  goldat10                  57300 non-null  float64
 39  xpat10                    57300 non-null  float64
 40  csat10                    57300 non-null  float64
 41  opp_goldat10              57300 non-null  float64
 42  opp_xpat10                57300 non-null  float64
 43  opp_csat10                57300 non-null  float64
 44  golddiffat10              57300 non-null  float64
 45  xpdiffat10                57300 non-null  float64
 46  csdiffat10                57300 non-null  float64
 47  goldat15                  57300 non-null  float64
 48  xpat15                    57300 non-null  float64
 49  csat15                    57300 non-null  float64
 50  opp_goldat15              57300 non-null  float64
 51  opp_xpat15                57300 non-null  float64
 52  opp_csat15                57300 non-null  float64
 53  golddiffat15              57300 non-null  float64
 54  xpdiffat15                57300 non-null  float64
 55  csdiffat15                57300 non-null  float64
dtypes: float64(37), int64(16), object(3)
memory usage: 24.9+ MB

In [80]:
for i in teams_remove:
    team_stats_df_no_na.drop(i, inplace = True, axis = 1)
    
team_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11460 entries, 10 to 69707
Data columns (total 79 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    11452 non-null  object
 1   side                      11460 non-null  object
 2   gamelength                11460 non-null  int64
 3   result                    11460 non-null  int64
 4   kills                     11460 non-null  int64
 5   deaths                    11460 non-null  int64
 6   assists                   11460 non-null  int64
 7   teamkills                 11460 non-null  int64
 8   teamdeaths                11460 non-null  int64
 9   doublekills               11460 non-null  float64
 10  triplekills               11460 non-null  float64
 11  quadrakills               11460 non-null  float64
 12  pentakills                11460 non-null  float64
 13  firstblood                11460 non-null  float64
 14  team kpm                  11460 non-null  float64
 15  ckpm                      11460 non-null  float64
 16  firstdragon               11458 non-null  float64
 17  dragons                   11460 non-null  float64
 18  opp_dragons               11460 non-null  float64
 19  elementaldrakes           11460 non-null  float64
 20  opp_elementaldrakes       11460 non-null  float64
 21  infernals                 11460 non-null  float64
 22  mountains                 11460 non-null  float64
 23  clouds                    11460 non-null  float64
 24  oceans                    11460 non-null  float64
 25  elders                    11460 non-null  float64
 26  opp_elders                11460 non-null  float64
 27  firstherald               11460 non-null  float64
 28  heralds                   11460 non-null  float64
 29  opp_heralds               11460 non-null  float64
 30  firstbaron                11168 non-null  float64
 31  barons                    11460 non-null  float64
 32  opp_barons                11460 non-null  float64
 33  firsttower                11460 non-null  float64
 34  towers                    11460 non-null  float64
 35  opp_towers                11460 non-null  float64
 36  firstmidtower             11460 non-null  float64
 37  firsttothreetowers        11460 non-null  float64
 38  inhibitors                11460 non-null  float64
 39  opp_inhibitors            11460 non-null  float64
 40  damagetochampions         11460 non-null  int64
 41  dpm                       11460 non-null  float64
 42  damagetakenperminute      11460 non-null  float64
 43  damagemitigatedperminute  11460 non-null  float64
 44  wardsplaced               11460 non-null  int64
 45  wpm                       11460 non-null  float64
 46  wardskilled               11460 non-null  int64
 47  wcpm                      11460 non-null  float64
 48  controlwardsbought        11460 non-null  int64
 49  visionscore               11460 non-null  float64
 50  vspm                      11460 non-null  float64
 51  totalgold                 11460 non-null  int64
 52  earnedgold                11460 non-null  int64
 53  earned gpm                11460 non-null  float64
 54  goldspent                 11460 non-null  float64
 55  gspd                      11460 non-null  float64
 56  minionkills               8188 non-null   float64
 57  monsterkills              11460 non-null  int64
 58  monsterkillsownjungle     11460 non-null  int64
 59  monsterkillsenemyjungle   11460 non-null  int64
 60  cspm                      8188 non-null   float64
 61  goldat10                  11460 non-null  float64
 62  xpat10                    11460 non-null  float64
 63  csat10                    11460 non-null  float64
 64  opp_goldat10              11460 non-null  float64
 65  opp_xpat10                11460 non-null  float64
 66  opp_csat10                11460 non-null  float64
 67  golddiffat10              11460 non-null  float64
 68  xpdiffat10                11460 non-null  float64
 69  csdiffat10                11460 non-null  float64
 70  goldat15                  11460 non-null  float64
 71  xpat15                    11460 non-null  float64
 72  csat15                    11460 non-null  float64
 73  opp_goldat15              11460 non-null  float64
 74  opp_xpat15                11460 non-null  float64
 75  opp_csat15                11460 non-null  float64
 76  golddiffat15              11460 non-null  float64
 77  xpdiffat15                11460 non-null  float64
 78  csdiffat15                11460 non-null  float64
dtypes: float64(61), int64(16), object(2)
memory usage: 7.0+ MB

C:\Users\kesha\anaconda3\envs\ml\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [25]:
player_stats_df_no_na.head()

,gameid,side,position,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
0,ESPORTSTMNT03/1241318,Blue,top,2220,1,0,3,7,17,11,...,23.0,4888.0,7368.0,131.0,4723.0,7202.0,118.0,165.0,166.0,13.0
1,ESPORTSTMNT03/1241318,Blue,jng,2220,1,4,0,9,17,11,...,-10.0,4385.0,4817.0,91.0,4784.0,4667.0,98.0,-399.0,150.0,-7.0
2,ESPORTSTMNT03/1241318,Blue,mid,2220,1,5,2,5,17,11,...,-9.0,4809.0,6275.0,129.0,5218.0,8112.0,140.0,-409.0,-1837.0,-11.0
3,ESPORTSTMNT03/1241318,Blue,bot,2220,1,7,1,9,17,11,...,3.0,4915.0,4959.0,136.0,4864.0,5360.0,135.0,51.0,-401.0,1.0
4,ESPORTSTMNT03/1241318,Blue,sup,2220,1,1,5,3,17,11,...,1.0,2956.0,3800.0,20.0,3189.0,3543.0,28.0,-233.0,257.0,-8.0

In [26]:
team_stats_df_no_na.head()

,gameid,side,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,17,11,3.0,...,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0
11,ESPORTSTMNT03/1241318,Red,2220,0,11,17,25,11,17,0.0,...,-8.0,22778.0,28884.0,519.0,21953.0,27219.0,507.0,825.0,1665.0,12.0
22,ESPORTSTMNT03/1241322,Blue,2227,0,5,21,16,5,21,1.0,...,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0
23,ESPORTSTMNT03/1241322,Red,2227,1,21,5,41,21,5,2.0,...,34.0,27198.0,31702.0,557.0,21714.0,26869.0,501.0,5484.0,4833.0,56.0
34,ESPORTSTMNT03/1241324,Blue,1711,1,21,4,34,21,4,4.0,...,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0

In [27]:
player_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57300 entries, 0 to 69705
Data columns (total 56 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    57260 non-null  object
 1   side                      57300 non-null  object
 2   position                  57300 non-null  object
 3   gamelength                57300 non-null  int64
 4   result                    57300 non-null  int64
 5   kills                     57300 non-null  int64
 6   deaths                    57300 non-null  int64
 7   assists                   57300 non-null  int64
 8   teamkills                 57300 non-null  int64
 9   teamdeaths                57300 non-null  int64
 10  doublekills               57300 non-null  float64
 11  triplekills               57300 non-null  float64
 12  quadrakills               57300 non-null  float64
 13  pentakills                57300 non-null  float64
 14  firstbloodkill            57300 non-null  float64
 15  damagetochampions         57300 non-null  int64
 16  dpm                       57300 non-null  float64
 17  damageshare               57300 non-null  float64
 18  damagetakenperminute      57300 non-null  float64
 19  damagemitigatedperminute  57300 non-null  float64
 20  wardsplaced               57300 non-null  int64
 21  wpm                       57300 non-null  float64
 22  wardskilled               57300 non-null  int64
 23  wcpm                      57300 non-null  float64
 24  controlwardsbought        57300 non-null  int64
 25  visionscore               57300 non-null  float64
 26  vspm                      57300 non-null  float64
 27  totalgold                 57300 non-null  int64
 28  earnedgold                57300 non-null  int64
 29  earned gpm                57300 non-null  float64
 30  earnedgoldshare           57300 non-null  float64
 31  goldspent                 57300 non-null  float64
 32  total cs                  57300 non-null  float64
 33  minionkills               57300 non-null  float64
 34  monsterkills              57300 non-null  int64
 35  monsterkillsownjungle     57300 non-null  int64
 36  monsterkillsenemyjungle   57300 non-null  int64
 37  cspm                      57300 non-null  float64
 38  goldat10                  57300 non-null  float64
 39  xpat10                    57300 non-null  float64
 40  csat10                    57300 non-null  float64
 41  opp_goldat10              57300 non-null  float64
 42  opp_xpat10                57300 non-null  float64
 43  opp_csat10                57300 non-null  float64
 44  golddiffat10              57300 non-null  float64
 45  xpdiffat10                57300 non-null  float64
 46  csdiffat10                57300 non-null  float64
 47  goldat15                  57300 non-null  float64
 48  xpat15                    57300 non-null  float64
 49  csat15                    57300 non-null  float64
 50  opp_goldat15              57300 non-null  float64
 51  opp_xpat15                57300 non-null  float64
 52  opp_csat15                57300 non-null  float64
 53  golddiffat15              57300 non-null  float64
 54  xpdiffat15                57300 non-null  float64
 55  csdiffat15                57300 non-null  float64
dtypes: float64(37), int64(16), object(3)
memory usage: 24.9+ MB

In [28]:
team_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11460 entries, 10 to 69707
Data columns (total 79 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    11452 non-null  object
 1   side                      11460 non-null  object
 2   gamelength                11460 non-null  int64
 3   result                    11460 non-null  int64
 4   kills                     11460 non-null  int64
 5   deaths                    11460 non-null  int64
 6   assists                   11460 non-null  int64
 7   teamkills                 11460 non-null  int64
 8   teamdeaths                11460 non-null  int64
 9   doublekills               11460 non-null  float64
 10  triplekills               11460 non-null  float64
 11  quadrakills               11460 non-null  float64
 12  pentakills                11460 non-null  float64
 13  firstblood                11460 non-null  float64
 14  team kpm                  11460 non-null  float64
 15  ckpm                      11460 non-null  float64
 16  firstdragon               11458 non-null  float64
 17  dragons                   11460 non-null  float64
 18  opp_dragons               11460 non-null  float64
 19  elementaldrakes           11460 non-null  float64
 20  opp_elementaldrakes       11460 non-null  float64
 21  infernals                 11460 non-null  float64
 22  mountains                 11460 non-null  float64
 23  clouds                    11460 non-null  float64
 24  oceans                    11460 non-null  float64
 25  elders                    11460 non-null  float64
 26  opp_elders                11460 non-null  float64
 27  firstherald               11460 non-null  float64
 28  heralds                   11460 non-null  float64
 29  opp_heralds               11460 non-null  float64
 30  firstbaron                11168 non-null  float64
 31  barons                    11460 non-null  float64
 32  opp_barons                11460 non-null  float64
 33  firsttower                11460 non-null  float64
 34  towers                    11460 non-null  float64
 35  opp_towers                11460 non-null  float64
 36  firstmidtower             11460 non-null  float64
 37  firsttothreetowers        11460 non-null  float64
 38  inhibitors                11460 non-null  float64
 39  opp_inhibitors            11460 non-null  float64
 40  damagetochampions         11460 non-null  int64
 41  dpm                       11460 non-null  float64
 42  damagetakenperminute      11460 non-null  float64
 43  damagemitigatedperminute  11460 non-null  float64
 44  wardsplaced               11460 non-null  int64
 45  wpm                       11460 non-null  float64
 46  wardskilled               11460 non-null  int64
 47  wcpm                      11460 non-null  float64
 48  controlwardsbought        11460 non-null  int64
 49  visionscore               11460 non-null  float64
 50  vspm                      11460 non-null  float64
 51  totalgold                 11460 non-null  int64
 52  earnedgold                11460 non-null  int64
 53  earned gpm                11460 non-null  float64
 54  goldspent                 11460 non-null  float64
 55  gspd                      11460 non-null  float64
 56  minionkills               8188 non-null   float64
 57  monsterkills              11460 non-null  int64
 58  monsterkillsownjungle     11460 non-null  int64
 59  monsterkillsenemyjungle   11460 non-null  int64
 60  cspm                      8188 non-null   float64
 61  goldat10                  11460 non-null  float64
 62  xpat10                    11460 non-null  float64
 63  csat10                    11460 non-null  float64
 64  opp_goldat10              11460 non-null  float64
 65  opp_xpat10                11460 non-null  float64
 66  opp_csat10                11460 non-null  float64
 67  golddiffat10              11460 non-null  float64
 68  xpdiffat10                11460 non-null  float64
 69  csdiffat10                11460 non-null  float64
 70  goldat15                  11460 non-null  float64
 71  xpat15                    11460 non-null  float64
 72  csat15                    11460 non-null  float64
 73  opp_goldat15              11460 non-null  float64
 74  opp_xpat15                11460 non-null  float64
 75  opp_csat15                11460 non-null  float64
 76  golddiffat15              11460 non-null  float64
 77  xpdiffat15                11460 non-null  float64
 78  csdiffat15                11460 non-null  float64
dtypes: float64(61), int64(16), object(2)
memory usage: 7.0+ MB

In [29]:
team_stats_df_no_na[:3]

,gameid,side,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,...,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,17,11,3.0,...,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0
11,ESPORTSTMNT03/1241318,Red,2220,0,11,17,25,11,17,0.0,...,-8.0,22778.0,28884.0,519.0,21953.0,27219.0,507.0,825.0,1665.0,12.0
22,ESPORTSTMNT03/1241322,Blue,2227,0,5,21,16,5,21,1.0,...,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0

#### Se haran varios cambios para poder realizar la tarea de prediccion que se tiene en mente
- se combinara las entradas de ambos equipos a una unica entrada que contiene la informacion de ambos equipos
- el atributo result cambiara de ser representado por 1 el vencedor a 1 = victoria equipo azul, -1 = victoria equipo rojo
- todas las columnas que contengan informacion "espejo" es decir representen informacion global del juego solo se contendran una vez

#### cambie las preferencias de pandas para poder ver la informacion completa de cada entrada, esto es para determinar de que manera se hara la condensacion de informacion, debemos recordar que cada 2 entradas equivale a un unico juego, por lo tanto debemos considerar como unir ambas entradas para poder llevar a cabo la tarea de prediccion que se tiene planeada para etapas posteriores

#### Limpiando aun mas nuestro dataframe de equipos para condensar toda la informacion en una unica entrada. El dataframe nos facilita un poco la tarea gracias a la existencia de todas las entradas con el prefijo "opp_" todas estas entradas son la informacion del oponente, asi que unicamente se debe de determinar que informacion del segundo euqipo no se encuentra ya en la entrada original del primer equipo y agregarla con un prefijo "opp_"

In [81]:
pd.set_option('display.max_columns', None)

In [31]:
team_stats_df_no_na[:2]

,gameid,side,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,inhibitors,opp_inhibitors,damagetochampions,dpm,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,goldspent,gspd,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,17,11,3.0,0.0,0.0,0.0,0.0,0.4595,0.7568,0.0,2.0,3.0,2.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,8.0,4.0,0.0,0.0,1.0,0.0,77679,2099.4324,1975.3243,2302.4595,191,5.1622,97,2.6216,67,380.0,10.2703,68927,44905,1213.6486,62275.0,0.004023,1049.0,216,166,0,34.1892,14615.0,17845.0,330.0,14498.0,17982.0,322.0,117.0,-137.0,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0
11,ESPORTSTMNT03/1241318,Red,2220,0,11,17,25,11,17,0.0,0.0,0.0,0.0,1.0,0.2973,0.7568,1.0,3.0,2.0,3.0,2.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,4.0,8.0,1.0,1.0,0.0,1.0,48685,1315.8108,2934.9459,3135.6486,172,4.6486,91,2.4595,69,318.0,8.5946,62709,38687,1045.5946,62025.0,-0.004023,1021.0,271,193,5,34.9189,14498.0,17982.0,322.0,14615.0,17845.0,330.0,-117.0,137.0,-8.0,22778.0,28884.0,519.0,21953.0,27219.0,507.0,825.0,1665.0,12.0

#### columnas a eliminar para equipos:
- teamkills
- teamdeaths

#### columnas a agregar con prefijo "opp_" para equipos:

- kills
- deaths
- assists
- doublekills
- triplekills
- quadrakills
- pentakills
- firstblood
- team kpm
- infernals
- mountains
- clouds
- oceans
- firstherald
- firstbaron
- firsttower
- firstmidtower
- firsttothreetowers
- damagetochampions
- dpm
- damagetakenperminute
- damagemitigatedperminute
- wardsplaced
- wpm
- wardskilled
- wcpm
- controlwardsbought
- visionscore
- vspm
- totalgold
- earnedgold
- earned gpm
- goldspent
- minionkills
- monstekills
- monsterkillsownjungle
- monsterkillsenemyjungle
- cspm

#### como funcionara esto? todas estas columnas con prefijo "opp_" seran extraidas de las entradas del equipo 2 y seran reasignadas a las estadisticas en el equipo 1, la columna que indica equipo sera eliminada, la entrada del equipo2 sera eliminada por completo

In [32]:
team_stats_df_no_na.drop("teamkills", inplace = True, axis = 1)
player_stats_df_no_na.drop("teamkills", inplace = True, axis = 1)
team_stats_df_no_na.drop("teamdeaths", inplace = True, axis = 1)
player_stats_df_no_na.drop("teamdeaths", inplace = True, axis = 1)

C:\Users\kesha\anaconda3\envs\ml\lib\site-packages\pandas\core\frame.py:3990: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [33]:
team_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11460 entries, 10 to 69707
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    11452 non-null  object
 1   side                      11460 non-null  object
 2   gamelength                11460 non-null  int64
 3   result                    11460 non-null  int64
 4   kills                     11460 non-null  int64
 5   deaths                    11460 non-null  int64
 6   assists                   11460 non-null  int64
 7   doublekills               11460 non-null  float64
 8   triplekills               11460 non-null  float64
 9   quadrakills               11460 non-null  float64
 10  pentakills                11460 non-null  float64
 11  firstblood                11460 non-null  float64
 12  team kpm                  11460 non-null  float64
 13  ckpm                      11460 non-null  float64
 14  firstdragon               11458 non-null  float64
 15  dragons                   11460 non-null  float64
 16  opp_dragons               11460 non-null  float64
 17  elementaldrakes           11460 non-null  float64
 18  opp_elementaldrakes       11460 non-null  float64
 19  infernals                 11460 non-null  float64
 20  mountains                 11460 non-null  float64
 21  clouds                    11460 non-null  float64
 22  oceans                    11460 non-null  float64
 23  elders                    11460 non-null  float64
 24  opp_elders                11460 non-null  float64
 25  firstherald               11460 non-null  float64
 26  heralds                   11460 non-null  float64
 27  opp_heralds               11460 non-null  float64
 28  firstbaron                11168 non-null  float64
 29  barons                    11460 non-null  float64
 30  opp_barons                11460 non-null  float64
 31  firsttower                11460 non-null  float64
 32  towers                    11460 non-null  float64
 33  opp_towers                11460 non-null  float64
 34  firstmidtower             11460 non-null  float64
 35  firsttothreetowers        11460 non-null  float64
 36  inhibitors                11460 non-null  float64
 37  opp_inhibitors            11460 non-null  float64
 38  damagetochampions         11460 non-null  int64
 39  dpm                       11460 non-null  float64
 40  damagetakenperminute      11460 non-null  float64
 41  damagemitigatedperminute  11460 non-null  float64
 42  wardsplaced               11460 non-null  int64
 43  wpm                       11460 non-null  float64
 44  wardskilled               11460 non-null  int64
 45  wcpm                      11460 non-null  float64
 46  controlwardsbought        11460 non-null  int64
 47  visionscore               11460 non-null  float64
 48  vspm                      11460 non-null  float64
 49  totalgold                 11460 non-null  int64
 50  earnedgold                11460 non-null  int64
 51  earned gpm                11460 non-null  float64
 52  goldspent                 11460 non-null  float64
 53  gspd                      11460 non-null  float64
 54  minionkills               8188 non-null   float64
 55  monsterkills              11460 non-null  int64
 56  monsterkillsownjungle     11460 non-null  int64
 57  monsterkillsenemyjungle   11460 non-null  int64
 58  cspm                      8188 non-null   float64
 59  goldat10                  11460 non-null  float64
 60  xpat10                    11460 non-null  float64
 61  csat10                    11460 non-null  float64
 62  opp_goldat10              11460 non-null  float64
 63  opp_xpat10                11460 non-null  float64
 64  opp_csat10                11460 non-null  float64
 65  golddiffat10              11460 non-null  float64
 66  xpdiffat10                11460 non-null  float64
 67  csdiffat10                11460 non-null  float64
 68  goldat15                  11460 non-null  float64
 69  xpat15                    11460 non-null  float64
 70  csat15                    11460 non-null  float64
 71  opp_goldat15              11460 non-null  float64
 72  opp_xpat15                11460 non-null  float64
 73  opp_csat15                11460 non-null  float64
 74  golddiffat15              11460 non-null  float64
 75  xpdiffat15                11460 non-null  float64
 76  csdiffat15                11460 non-null  float64
dtypes: float64(61), int64(14), object(2)
memory usage: 6.8+ MB

In [44]:
kills = []
deaths = []
assists = []
doublekills = []
triplekills = []
quadrakills = []
pentakills = []
firstblood = []
team_kpm = []
infernals = []
mountains = []
clouds = []
oceans = []
firstherald = []
firstbaron = []
firsttower = []
firstmidtower = []
firsttothreetowers = []
damagetochampions = []
dpm = []
damagetakenperminute = []
damagemitigatedperminute = []
wardsplaced = []
wpm = []
wardskilled = []
wcpm = []
controlwardsbought = []
visionscore = []
vspm = []
totalgold = []
earnedgold = []
earnedgpm = []
goldspent = []
minionkills = []
monsterkills = []
monsterkillsownjungle = []
monsterkillsenemyjungle = []
cspm = []

In [34]:
import copy
team_stats_df_no_na_bk = copy.copy(team_stats_df_no_na)

In [ ]:
team_stats_df_no_na = copy.copy(team_stats_df_no_na_bk)

In [ ]:
"""i = 0
while i < len(team_stats_df_no_na_bk):
    if i != 0 and i % 2 != 0:
        if team_stats_df_no_na.iloc[i]['result'] == 1:
            team_stats_df_no_na.iloc[i - 1] = -1
        
        kills.append(team_stats_df_no_na.iloc[i]['kills'])
        deaths.append(team_stats_df_no_na.iloc[i]['deaths'])
        assists.append(team_stats_df_no_na.iloc[i]['assists'])
        doublekills.append(team_stats_df_no_na.iloc[i]['doublekills'])
        triplekills.append(team_stats_df_no_na.iloc[i]['triplekills'])
        quadrakills.append(team_stats_df_no_na.iloc[i]['quadrakills'])
        pentakills.append(team_stats_df_no_na.iloc[i]['pentakills'])
        firstblood.append(team_stats_df_no_na.iloc[i]['firstblood'])
        team_kpm.append(team_stats_df_no_na.iloc[i]['team kpm'])
        infernals.append(team_stats_df_no_na.iloc[i]['infernals'])
        mountains.append(team_stats_df_no_na.iloc[i]['mountains'])
        clouds.append(team_stats_df_no_na.iloc[i]['clouds'])
        oceans.append(team_stats_df_no_na.iloc[i]['oceans'])
        firstherald.append(team_stats_df_no_na.iloc[i]['firstherald'])
        firstbaron.append(team_stats_df_no_na.iloc[i]['firstbaron'])
        firsttower.append(team_stats_df_no_na.iloc[i]['firsttower'])
        firstmidtower.append(team_stats_df_no_na.iloc[i]['firstmidtower'])
        firsttothreetowers.append(team_stats_df_no_na.iloc[i]['firsttothreetowers'])
        damagetochampions.append(team_stats_df_no_na.iloc[i]['damagetochampions'])
        dpm.append(team_stats_df_no_na.iloc[i]['dpm'])
        damagetakenperminute.append(team_stats_df_no_na.iloc[i]['damagetakenperminute'])
        damagemitigatedperminute.append(team_stats_df_no_na.iloc[i]['damagemitigatedperminute'])
        wardsplaced.append(team_stats_df_no_na.iloc[i]['wardsplaced'])
        wpm.append(team_stats_df_no_na.iloc[i]['wpm'])
        wardskilled.append(team_stats_df_no_na.iloc[i]['wardskilled'])
        wcpm.append(team_stats_df_no_na.iloc[i]['wcpm'])
        controlwardsbought.append(team_stats_df_no_na.iloc[i]['controlwardsbought'])
        visionscore.append(team_stats_df_no_na.iloc[i]['visionscore'])
        vspm.append(team_stats_df_no_na.iloc[i]['vspm'])
        totalgold.append(team_stats_df_no_na.iloc[i]['totalgold'])
        earnedgold.append(team_stats_df_no_na.iloc[i]['earnedgold'])
        earnedgpm.append(team_stats_df_no_na.iloc[i]['earned gpm'])
        goldspent.append(team_stats_df_no_na.iloc[i]['goldspent'])
        minionkills.append(team_stats_df_no_na.iloc[i]['minionkills'])
        monsterkills.append(team_stats_df_no_na.iloc[i]['monsterkills'])
        monsterkillsownjungle.append(team_stats_df_no_na.iloc[i]['monsterkillsownjungle'])
        monsterkillsenemyjungle.append(team_stats_df_no_na.iloc[i]['monsterkillsenemyjungle'])
        cspm.append(team_stats_df_no_na.iloc[i]['cspm'])
        
        team_stats_df_no_na.drop(team_stats_df_no_na.index[i], inplace = True, axis = 0)
        
        i += 1"""

In [ ]:
#prueba = copy.copy(team_stats_df_no_na)
#prueba.index[0]

In [ ]:
#prueba.drop(prueba.index[0], inplace = True, axis = 0)

In [ ]:
#prueba.index[0]

In [ ]:
#team_stats_df_no_na.iloc[2]['result']

In [36]:
team_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11460 entries, 10 to 69707
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    11452 non-null  object
 1   side                      11460 non-null  object
 2   gamelength                11460 non-null  int64
 3   result                    11460 non-null  int64
 4   kills                     11460 non-null  int64
 5   deaths                    11460 non-null  int64
 6   assists                   11460 non-null  int64
 7   doublekills               11460 non-null  float64
 8   triplekills               11460 non-null  float64
 9   quadrakills               11460 non-null  float64
 10  pentakills                11460 non-null  float64
 11  firstblood                11460 non-null  float64
 12  team kpm                  11460 non-null  float64
 13  ckpm                      11460 non-null  float64
 14  firstdragon               11458 non-null  float64
 15  dragons                   11460 non-null  float64
 16  opp_dragons               11460 non-null  float64
 17  elementaldrakes           11460 non-null  float64
 18  opp_elementaldrakes       11460 non-null  float64
 19  infernals                 11460 non-null  float64
 20  mountains                 11460 non-null  float64
 21  clouds                    11460 non-null  float64
 22  oceans                    11460 non-null  float64
 23  elders                    11460 non-null  float64
 24  opp_elders                11460 non-null  float64
 25  firstherald               11460 non-null  float64
 26  heralds                   11460 non-null  float64
 27  opp_heralds               11460 non-null  float64
 28  firstbaron                11168 non-null  float64
 29  barons                    11460 non-null  float64
 30  opp_barons                11460 non-null  float64
 31  firsttower                11460 non-null  float64
 32  towers                    11460 non-null  float64
 33  opp_towers                11460 non-null  float64
 34  firstmidtower             11460 non-null  float64
 35  firsttothreetowers        11460 non-null  float64
 36  inhibitors                11460 non-null  float64
 37  opp_inhibitors            11460 non-null  float64
 38  damagetochampions         11460 non-null  int64
 39  dpm                       11460 non-null  float64
 40  damagetakenperminute      11460 non-null  float64
 41  damagemitigatedperminute  11460 non-null  float64
 42  wardsplaced               11460 non-null  int64
 43  wpm                       11460 non-null  float64
 44  wardskilled               11460 non-null  int64
 45  wcpm                      11460 non-null  float64
 46  controlwardsbought        11460 non-null  int64
 47  visionscore               11460 non-null  float64
 48  vspm                      11460 non-null  float64
 49  totalgold                 11460 non-null  int64
 50  earnedgold                11460 non-null  int64
 51  earned gpm                11460 non-null  float64
 52  goldspent                 11460 non-null  float64
 53  gspd                      11460 non-null  float64
 54  minionkills               8188 non-null   float64
 55  monsterkills              11460 non-null  int64
 56  monsterkillsownjungle     11460 non-null  int64
 57  monsterkillsenemyjungle   11460 non-null  int64
 58  cspm                      8188 non-null   float64
 59  goldat10                  11460 non-null  float64
 60  xpat10                    11460 non-null  float64
 61  csat10                    11460 non-null  float64
 62  opp_goldat10              11460 non-null  float64
 63  opp_xpat10                11460 non-null  float64
 64  opp_csat10                11460 non-null  float64
 65  golddiffat10              11460 non-null  float64
 66  xpdiffat10                11460 non-null  float64
 67  csdiffat10                11460 non-null  float64
 68  goldat15                  11460 non-null  float64
 69  xpat15                    11460 non-null  float64
 70  csat15                    11460 non-null  float64
 71  opp_goldat15              11460 non-null  float64
 72  opp_xpat15                11460 non-null  float64
 73  opp_csat15                11460 non-null  float64
 74  golddiffat15              11460 non-null  float64
 75  xpdiffat15                11460 non-null  float64
 76  csdiffat15                11460 non-null  float64
dtypes: float64(61), int64(14), object(2)
memory usage: 6.8+ MB

In [35]:
blue_teams_df = team_stats_df_no_na[team_stats_df_no_na['side'] == 'Blue']
blue_teams_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5730 entries, 10 to 69706
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    5726 non-null   object
 1   side                      5730 non-null   object
 2   gamelength                5730 non-null   int64
 3   result                    5730 non-null   int64
 4   kills                     5730 non-null   int64
 5   deaths                    5730 non-null   int64
 6   assists                   5730 non-null   int64
 7   doublekills               5730 non-null   float64
 8   triplekills               5730 non-null   float64
 9   quadrakills               5730 non-null   float64
 10  pentakills                5730 non-null   float64
 11  firstblood                5730 non-null   float64
 12  team kpm                  5730 non-null   float64
 13  ckpm                      5730 non-null   float64
 14  firstdragon               5729 non-null   float64
 15  dragons                   5730 non-null   float64
 16  opp_dragons               5730 non-null   float64
 17  elementaldrakes           5730 non-null   float64
 18  opp_elementaldrakes       5730 non-null   float64
 19  infernals                 5730 non-null   float64
 20  mountains                 5730 non-null   float64
 21  clouds                    5730 non-null   float64
 22  oceans                    5730 non-null   float64
 23  elders                    5730 non-null   float64
 24  opp_elders                5730 non-null   float64
 25  firstherald               5730 non-null   float64
 26  heralds                   5730 non-null   float64
 27  opp_heralds               5730 non-null   float64
 28  firstbaron                5584 non-null   float64
 29  barons                    5730 non-null   float64
 30  opp_barons                5730 non-null   float64
 31  firsttower                5730 non-null   float64
 32  towers                    5730 non-null   float64
 33  opp_towers                5730 non-null   float64
 34  firstmidtower             5730 non-null   float64
 35  firsttothreetowers        5730 non-null   float64
 36  inhibitors                5730 non-null   float64
 37  opp_inhibitors            5730 non-null   float64
 38  damagetochampions         5730 non-null   int64
 39  dpm                       5730 non-null   float64
 40  damagetakenperminute      5730 non-null   float64
 41  damagemitigatedperminute  5730 non-null   float64
 42  wardsplaced               5730 non-null   int64
 43  wpm                       5730 non-null   float64
 44  wardskilled               5730 non-null   int64
 45  wcpm                      5730 non-null   float64
 46  controlwardsbought        5730 non-null   int64
 47  visionscore               5730 non-null   float64
 48  vspm                      5730 non-null   float64
 49  totalgold                 5730 non-null   int64
 50  earnedgold                5730 non-null   int64
 51  earned gpm                5730 non-null   float64
 52  goldspent                 5730 non-null   float64
 53  gspd                      5730 non-null   float64
 54  minionkills               4094 non-null   float64
 55  monsterkills              5730 non-null   int64
 56  monsterkillsownjungle     5730 non-null   int64
 57  monsterkillsenemyjungle   5730 non-null   int64
 58  cspm                      4094 non-null   float64
 59  goldat10                  5730 non-null   float64
 60  xpat10                    5730 non-null   float64
 61  csat10                    5730 non-null   float64
 62  opp_goldat10              5730 non-null   float64
 63  opp_xpat10                5730 non-null   float64
 64  opp_csat10                5730 non-null   float64
 65  golddiffat10              5730 non-null   float64
 66  xpdiffat10                5730 non-null   float64
 67  csdiffat10                5730 non-null   float64
 68  goldat15                  5730 non-null   float64
 69  xpat15                    5730 non-null   float64
 70  csat15                    5730 non-null   float64
 71  opp_goldat15              5730 non-null   float64
 72  opp_xpat15                5730 non-null   float64
 73  opp_csat15                5730 non-null   float64
 74  golddiffat15              5730 non-null   float64
 75  xpdiffat15                5730 non-null   float64
 76  csdiffat15                5730 non-null   float64
dtypes: float64(61), int64(14), object(2)
memory usage: 3.4+ MB

In [37]:
red_teams_df =  team_stats_df_no_na[team_stats_df_no_na['side'] == 'Red']
red_teams_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5730 entries, 11 to 69707
Data columns (total 77 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    5726 non-null   object
 1   side                      5730 non-null   object
 2   gamelength                5730 non-null   int64
 3   result                    5730 non-null   int64
 4   kills                     5730 non-null   int64
 5   deaths                    5730 non-null   int64
 6   assists                   5730 non-null   int64
 7   doublekills               5730 non-null   float64
 8   triplekills               5730 non-null   float64
 9   quadrakills               5730 non-null   float64
 10  pentakills                5730 non-null   float64
 11  firstblood                5730 non-null   float64
 12  team kpm                  5730 non-null   float64
 13  ckpm                      5730 non-null   float64
 14  firstdragon               5729 non-null   float64
 15  dragons                   5730 non-null   float64
 16  opp_dragons               5730 non-null   float64
 17  elementaldrakes           5730 non-null   float64
 18  opp_elementaldrakes       5730 non-null   float64
 19  infernals                 5730 non-null   float64
 20  mountains                 5730 non-null   float64
 21  clouds                    5730 non-null   float64
 22  oceans                    5730 non-null   float64
 23  elders                    5730 non-null   float64
 24  opp_elders                5730 non-null   float64
 25  firstherald               5730 non-null   float64
 26  heralds                   5730 non-null   float64
 27  opp_heralds               5730 non-null   float64
 28  firstbaron                5584 non-null   float64
 29  barons                    5730 non-null   float64
 30  opp_barons                5730 non-null   float64
 31  firsttower                5730 non-null   float64
 32  towers                    5730 non-null   float64
 33  opp_towers                5730 non-null   float64
 34  firstmidtower             5730 non-null   float64
 35  firsttothreetowers        5730 non-null   float64
 36  inhibitors                5730 non-null   float64
 37  opp_inhibitors            5730 non-null   float64
 38  damagetochampions         5730 non-null   int64
 39  dpm                       5730 non-null   float64
 40  damagetakenperminute      5730 non-null   float64
 41  damagemitigatedperminute  5730 non-null   float64
 42  wardsplaced               5730 non-null   int64
 43  wpm                       5730 non-null   float64
 44  wardskilled               5730 non-null   int64
 45  wcpm                      5730 non-null   float64
 46  controlwardsbought        5730 non-null   int64
 47  visionscore               5730 non-null   float64
 48  vspm                      5730 non-null   float64
 49  totalgold                 5730 non-null   int64
 50  earnedgold                5730 non-null   int64
 51  earned gpm                5730 non-null   float64
 52  goldspent                 5730 non-null   float64
 53  gspd                      5730 non-null   float64
 54  minionkills               4094 non-null   float64
 55  monsterkills              5730 non-null   int64
 56  monsterkillsownjungle     5730 non-null   int64
 57  monsterkillsenemyjungle   5730 non-null   int64
 58  cspm                      4094 non-null   float64
 59  goldat10                  5730 non-null   float64
 60  xpat10                    5730 non-null   float64
 61  csat10                    5730 non-null   float64
 62  opp_goldat10              5730 non-null   float64
 63  opp_xpat10                5730 non-null   float64
 64  opp_csat10                5730 non-null   float64
 65  golddiffat10              5730 non-null   float64
 66  xpdiffat10                5730 non-null   float64
 67  csdiffat10                5730 non-null   float64
 68  goldat15                  5730 non-null   float64
 69  xpat15                    5730 non-null   float64
 70  csat15                    5730 non-null   float64
 71  opp_goldat15              5730 non-null   float64
 72  opp_xpat15                5730 non-null   float64
 73  opp_csat15                5730 non-null   float64
 74  golddiffat15              5730 non-null   float64
 75  xpdiffat15                5730 non-null   float64
 76  csdiffat15                5730 non-null   float64
dtypes: float64(61), int64(14), object(2)
memory usage: 3.4+ MB

In [38]:
blue_teams_df.head()

,gameid,side,gamelength,result,kills,deaths,assists,doublekills,triplekills,quadrakills,pentakills,firstblood,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,inhibitors,opp_inhibitors,damagetochampions,dpm,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,goldspent,gspd,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,3.0,0.0,0.0,0.0,0.0,0.4595,0.7568,0.0,2.0,3.0,2.0,3.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,8.0,4.0,0.0,0.0,1.0,0.0,77679,2099.4324,1975.3243,2302.4595,191,5.1622,97,2.6216,67,380.0,10.2703,68927,44905,1213.6486,62275.0,0.004023,1049.0,216,166,0,34.1892,14615.0,17845.0,330.0,14498.0,17982.0,322.0,117.0,-137.0,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0
22,ESPORTSTMNT03/1241322,Blue,2227,0,5,21,16,1.0,0.0,0.0,0.0,0.0,0.1347,0.7005,0.0,1.0,4.0,1.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0,9.0,1.0,0.0,0.0,1.0,72963,1965.7746,2324.1042,2729.5016,144,3.8797,95,2.5595,58,254.0,6.8433,57283,33190,894.2075,56575.0,-0.122771,1011.0,183,151,1,32.1688,14180.0,16947.0,300.0,16194.0,19096.0,334.0,-2014.0,-2149.0,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0
34,ESPORTSTMNT03/1241324,Blue,1711,1,21,4,34,4.0,1.0,1.0,0.0,0.0,0.7364,0.8767,1.0,4.0,0.0,4.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,2.0,0.0,1.0,1.0,0.0,1.0,10.0,1.0,1.0,1.0,2.0,0.0,50728,1778.8895,2032.8112,2500.4676,111,3.8925,49,1.7183,42,262.0,9.1876,58078,39248,1376.3179,50660.0,0.225957,806.0,242,126,42,36.7504,15531.0,19034.0,365.0,14849.0,18419.0,340.0,682.0,615.0,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0
46,ESPORTSTMNT03/1241328,Blue,1999,0,4,17,8,0.0,0.0,0.0,0.0,0.0,0.1201,0.6303,1.0,2.0,3.0,2.0,3.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,2.0,0.0,3.0,9.0,0.0,0.0,0.0,1.0,35364,1061.4507,2155.9180,2295.1876,143,4.2921,57,1.7109,51,248.0,7.4437,50749,28981,869.8649,48400.0,-0.170132,813.0,206,150,12,30.5853,14313.0,16950.0,308.0,15892.0,17808.0,329.0,-1579.0,-858.0,-21.0,22329.0,26093.0,465.0,24800.0,29157.0,535.0,-2471.0,-3064.0,-70.0
58,ESPORTSTMNT03/1241386,Blue,1812,0,3,21,7,0.0,0.0,0.0,0.0,0.0,0.0993,0.7947,0.0,1.0,4.0,1.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,2.0,1.0,4.0,8.0,0.0,0.0,0.0,1.0,42830,1418.2119,2763.4768,2432.5828,106,3.5099,56,1.8543,49,196.0,6.4901,48633,28773,952.7483,47010.0,-0.096665,799.0,205,151,7,33.2450,15388.0,18396.0,337.0,16135.0,18709.0,325.0,-747.0,-313.0,12.0,24644.0,29576.0,550.0,23767.0,29371.0,524.0,877.0,205.0,26.0

In [41]:
blue_teams_df.replace(0, -1, inplace = True)

C:\Users\kesha\anaconda3\envs\ml\lib\site-packages\pandas\core\frame.py:4166: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().replace(

In [42]:
blue_teams_df.head()

,gameid,side,gamelength,result,kills,deaths,assists,doublekills,triplekills,quadrakills,pentakills,firstblood,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,inhibitors,opp_inhibitors,damagetochampions,dpm,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,goldspent,gspd,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,3.0,-1.0,-1.0,-1.0,-1.0,0.4595,0.7568,-1.0,2.0,3.0,2.0,3.0,-1.0,2.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,8.0,4.0,-1.0,-1.0,1.0,-1.0,77679,2099.4324,1975.3243,2302.4595,191,5.1622,97,2.6216,67,380.0,10.2703,68927,44905,1213.6486,62275.0,0.004023,1049.0,216,166,-1,34.1892,14615.0,17845.0,330.0,14498.0,17982.0,322.0,117.0,-137.0,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0
22,ESPORTSTMNT03/1241322,Blue,2227,-1,5,21,16,1.0,-1.0,-1.0,-1.0,-1.0,0.1347,0.7005,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,2.0,-1.0,2.0,9.0,1.0,-1.0,-1.0,1.0,72963,1965.7746,2324.1042,2729.5016,144,3.8797,95,2.5595,58,254.0,6.8433,57283,33190,894.2075,56575.0,-0.122771,1011.0,183,151,1,32.1688,14180.0,16947.0,300.0,16194.0,19096.0,334.0,-2014.0,-2149.0,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0
34,ESPORTSTMNT03/1241324,Blue,1711,1,21,4,34,4.0,1.0,1.0,-1.0,-1.0,0.7364,0.8767,1.0,4.0,-1.0,4.0,-1.0,-1.0,2.0,1.0,1.0,-1.0,-1.0,1.0,2.0,-1.0,1.0,1.0,-1.0,1.0,10.0,1.0,1.0,1.0,2.0,-1.0,50728,1778.8895,2032.8112,2500.4676,111,3.8925,49,1.7183,42,262.0,9.1876,58078,39248,1376.3179,50660.0,0.225957,806.0,242,126,42,36.7504,15531.0,19034.0,365.0,14849.0,18419.0,340.0,682.0,615.0,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0
46,ESPORTSTMNT03/1241328,Blue,1999,-1,4,17,8,-1.0,-1.0,-1.0,-1.0,-1.0,0.1201,0.6303,1.0,2.0,3.0,2.0,3.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,2.0,-1.0,3.0,9.0,-1.0,-1.0,-1.0,1.0,35364,1061.4507,2155.9180,2295.1876,143,4.2921,57,1.7109,51,248.0,7.4437,50749,28981,869.8649,48400.0,-0.170132,813.0,206,150,12,30.5853,14313.0,16950.0,308.0,15892.0,17808.0,329.0,-1579.0,-858.0,-21.0,22329.0,26093.0,465.0,24800.0,29157.0,535.0,-2471.0,-3064.0,-70.0
58,ESPORTSTMNT03/1241386,Blue,1812,-1,3,21,7,-1.0,-1.0,-1.0,-1.0,-1.0,0.0993,0.7947,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,2.0,1.0,4.0,8.0,-1.0,-1.0,-1.0,1.0,42830,1418.2119,2763.4768,2432.5828,106,3.5099,56,1.8543,49,196.0,6.4901,48633,28773,952.7483,47010.0,-0.096665,799.0,205,151,7,33.2450,15388.0,18396.0,337.0,16135.0,18709.0,325.0,-747.0,-313.0,12.0,24644.0,29576.0,550.0,23767.0,29371.0,524.0,877.0,205.0,26.0

In [45]:
new_cols = [kills, deaths, assists, doublekills, triplekills, quadrakills, pentakills, firstblood, team_kpm, infernals, mountains, clouds, oceans, firstherald, firstbaron, firsttower, firstmidtower, firsttothreetowers, damagetochampions, dpm, damagetakenperminute, damagemitigatedperminute, wardsplaced, wpm, wardskilled, wcpm, controlwardsbought, visionscore, vspm, totalgold, earnedgold, earnedgpm, goldspent, minionkills, monsterkills, monsterkillsownjungle, monsterkillsenemyjungle, cspm]
red_col_names = ['kills', 'deaths', 'assists', 'doublekills', 'triplekills', 'quadrakills', 'pentakills', 'firstblood', 'team kpm', 'infernals', 'mountains', 'clouds', 'oceans', 'firstherald', 'firstbaron', 'firsttower', 'firstmidtower', 'firsttothreetowers', 'damagetochampions', 'dpm', 'damagetakenperminute', 'damagemitigatedperminute', 'wardsplaced', 'wpm', 'wardskilled', 'wcpm', 'controlwardsbought', 'visionscore', 'vspm', 'totalgold', 'earnedgold', 'earned gpm', 'goldspent', 'minionkills', 'monsterkills', 'monsterkillsownjungle', 'monsterkillsenemyjungle', 'cspm']
for i in range(len(new_cols)):
    new_cols[i] =  red_teams_df[red_col_names[i]]

In [53]:
prueba = copy.copy(blue_teams_df)
opp_k = new_cols[0].tolist()

In [55]:
prueba["opp_kills"] = opp_k
prueba.head()

,gameid,side,gamelength,result,kills,deaths,assists,doublekills,triplekills,quadrakills,pentakills,firstblood,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,inhibitors,opp_inhibitors,damagetochampions,dpm,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,goldspent,gspd,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,opp_kills
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,3.0,-1.0,-1.0,-1.0,-1.0,0.4595,0.7568,-1.0,2.0,3.0,2.0,3.0,-1.0,2.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,8.0,4.0,-1.0,-1.0,1.0,-1.0,77679,2099.4324,1975.3243,2302.4595,191,5.1622,97,2.6216,67,380.0,10.2703,68927,44905,1213.6486,62275.0,0.004023,1049.0,216,166,-1,34.1892,14615.0,17845.0,330.0,14498.0,17982.0,322.0,117.0,-137.0,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0,11
22,ESPORTSTMNT03/1241322,Blue,2227,-1,5,21,16,1.0,-1.0,-1.0,-1.0,-1.0,0.1347,0.7005,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,2.0,-1.0,2.0,9.0,1.0,-1.0,-1.0,1.0,72963,1965.7746,2324.1042,2729.5016,144,3.8797,95,2.5595,58,254.0,6.8433,57283,33190,894.2075,56575.0,-0.122771,1011.0,183,151,1,32.1688,14180.0,16947.0,300.0,16194.0,19096.0,334.0,-2014.0,-2149.0,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0,21
34,ESPORTSTMNT03/1241324,Blue,1711,1,21,4,34,4.0,1.0,1.0,-1.0,-1.0,0.7364,0.8767,1.0,4.0,-1.0,4.0,-1.0,-1.0,2.0,1.0,1.0,-1.0,-1.0,1.0,2.0,-1.0,1.0,1.0,-1.0,1.0,10.0,1.0,1.0,1.0,2.0,-1.0,50728,1778.8895,2032.8112,2500.4676,111,3.8925,49,1.7183,42,262.0,9.1876,58078,39248,1376.3179,50660.0,0.225957,806.0,242,126,42,36.7504,15531.0,19034.0,365.0,14849.0,18419.0,340.0,682.0,615.0,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0,4
46,ESPORTSTMNT03/1241328,Blue,1999,-1,4,17,8,-1.0,-1.0,-1.0,-1.0,-1.0,0.1201,0.6303,1.0,2.0,3.0,2.0,3.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,2.0,-1.0,3.0,9.0,-1.0,-1.0,-1.0,1.0,35364,1061.4507,2155.9180,2295.1876,143,4.2921,57,1.7109,51,248.0,7.4437,50749,28981,869.8649,48400.0,-0.170132,813.0,206,150,12,30.5853,14313.0,16950.0,308.0,15892.0,17808.0,329.0,-1579.0,-858.0,-21.0,22329.0,26093.0,465.0,24800.0,29157.0,535.0,-2471.0,-3064.0,-70.0,17
58,ESPORTSTMNT03/1241386,Blue,1812,-1,3,21,7,-1.0,-1.0,-1.0,-1.0,-1.0,0.0993,0.7947,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,2.0,1.0,4.0,8.0,-1.0,-1.0,-1.0,1.0,42830,1418.2119,2763.4768,2432.5828,106,3.5099,56,1.8543,49,196.0,6.4901,48633,28773,952.7483,47010.0,-0.096665,799.0,205,151,7,33.2450,15388.0,18396.0,337.0,16135.0,18709.0,325.0,-747.0,-313.0,12.0,24644.0,29576.0,550.0,23767.0,29371.0,524.0,877.0,205.0,26.0,21

In [56]:
prueba2 = copy.copy(blue_teams_df)

In [57]:
opp = "opp_"
new_col_names = ['kills', 'deaths', 'assists', 'doublekills', 'triplekills', 'quadrakills', 'pentakills', 'firstblood', 'team_kpm', 'infernals', 'mountains', 'clouds', 'oceans', 'firstherald', 'firstbaron', 'firsttower', 'firstmidtower', 'firsttothreetowers', 'damagetochampions', 'dpm', 'damagetakenperminute', 'damagemitigatedperminute', 'wardsplaced', 'wpm', 'wardskilled', 'wcpm', 'controlwardsbought', 'visionscore', 'vspm', 'totalgold', 'earnedgold', 'earned_gpm', 'goldspent', 'minionkills', 'monsterkills', 'monsterkillsownjungle', 'monsterkillsenemyjungle', 'cspm']
for i in range(len(new_cols)):
    aux = new_cols[i].tolist()
    name = opp + new_col_names[i]
    prueba2[name] = aux

In [58]:
prueba2.head()

,gameid,side,gamelength,result,kills,deaths,assists,doublekills,triplekills,quadrakills,pentakills,firstblood,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,inhibitors,opp_inhibitors,damagetochampions,dpm,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,goldspent,gspd,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,opp_kills,opp_deaths,opp_assists,opp_doublekills,opp_triplekills,opp_quadrakills,opp_pentakills,opp_firstblood,opp_team_kpm,opp_infernals,opp_mountains,opp_clouds,opp_oceans,opp_firstherald,opp_firstbaron,opp_firsttower,opp_firstmidtower,opp_firsttothreetowers,opp_damagetochampions,opp_dpm,opp_damagetakenperminute,opp_damagemitigatedperminute,opp_wardsplaced,opp_wpm,opp_wardskilled,opp_wcpm,opp_controlwardsbought,opp_visionscore,opp_vspm,opp_totalgold,opp_earnedgold,opp_earned_gpm,opp_goldspent,opp_minionkills,opp_monsterkills,opp_monsterkillsownjungle,opp_monsterkillsenemyjungle,opp_cspm
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,3.0,-1.0,-1.0,-1.0,-1.0,0.4595,0.7568,-1.0,2.0,3.0,2.0,3.0,-1.0,2.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,8.0,4.0,-1.0,-1.0,1.0,-1.0,77679,2099.4324,1975.3243,2302.4595,191,5.1622,97,2.6216,67,380.0,10.2703,68927,44905,1213.6486,62275.0,0.004023,1049.0,216,166,-1,34.1892,14615.0,17845.0,330.0,14498.0,17982.0,322.0,117.0,-137.0,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0,11,17,25,0.0,0.0,0.0,0.0,1.0,0.2973,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,48685,1315.8108,2934.9459,3135.6486,172,4.6486,91,2.4595,69,318.0,8.5946,62709,38687,1045.5946,62025.0,1021.0,271,193,5,34.9189
22,ESPORTSTMNT03/1241322,Blue,2227,-1,5,21,16,1.0,-1.0,-1.0,-1.0,-1.0,0.1347,0.7005,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,2.0,-1.0,2.0,9.0,1.0,-1.0,-1.0,1.0,72963,1965.7746,2324.1042,2729.5016,144,3.8797,95,2.5595,58,254.0,6.8433,57283,33190,894.2075,56575.0,-0.122771,1011.0,183,151,1,32.1688,14180.0,16947.0,300.0,16194.0,19096.0,334.0,-2014.0,-2149.0,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0,21,5,41,2.0,0.0,0.0,0.0,1.0,0.5658,0.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,65542,1765.8374,2861.2214,3192.7167,195,5.2537,90,2.4248,53,397.0,10.6960,72004,47911,1290.8217,63975.0,976.0,270,126,48,33.5698
34,ESPORTSTMNT03/1241324,Blue,1711,1,21,4,34,4.0,1.0,1.0,-1.0,-1.0,0.7364,0.8767,1.0,4.0,-1.0,4.0,-1.0,-1.0,2.0,1.0,1.0,-1.0,-1.0,1.0,2.0,-1.0,1.0,1.0,-1.0,1.0,10.0,1.0,1.0,1.0,2.0,-1.0,50728,1778.8895,2032.8112,2500.4676,111,3.8925,49,1.7183,42,262.0,9.1876,58078,39248,1376.3179,50660.0,0.225957,806.0,242,126,42,36.7504,15531.0,19034.0,365.0,14849.0,18419.0,340.0,682.0,615.0,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0,4,21,11,1.0,0.0,0.0,0.0,1.0,0.1403,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29684,1040.9351,2298.7259,2011.3150,96,3.3665,48,1.6832,49,194.0,6.8030,42465,23635,828.8136,40375.0,748.0,136,107,0,30.9994
46,ESPORTSTMNT03/1241328,Blue,1999,-1,4,17,8,-1.0,-1.0,-1.0,-1.0,-1.0,0.1201,0.6303,1.0,2.0,3.0,2.0,3.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,2.0,-1.0,3.0,9.0,-1.0,-1.0,-1.0,1.0,35364,1061.4507,2155.9180,2295.1876,143,4.2921,57,1.7109,51,248.0,7.4437,50749,28981,869.8649,48400.0,-0.170132,813.0,206,150,12,30.5853,14313.0,16950.0,308.0,15892.0,17808.0,329.0,-1579.0,-858.0,-21.0,22329.0,26093.0,465.0,24800.0,29157.0,535.0,-2471.0,-3064.0,-70.0,17,4,33,3.0,1.0,1.0,1.0,1.0,0.5103,0.0,0.0,3.0,0.0,0.0,1.0,1.0,1.0,1.0,54828,1645.6628,1772.5963,2063.5918,141,4.2321,81,2.4312,65,345.0,10.3552,64845,43077,1292.9565,57400.0,911.0,238,148,26,34.4872
58,ESPORTSTMNT03/1241386,Blue,1812,-1,3,21,7,-1.0,-1.0,-1.0,-1.0,-1.0,0.0993,0.7947,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,2.0,1.0,4.0,8.0,-1.0,-1.0,-1.0,1.0,42830,1418.2119,2763.4768,2432.5828,106,3.5099,56,1.8543,49,196.0,6.4901,48633,28773,952.7483,47010.0,-0.096665,799.0,205,151,7,33.2450,15388.0,18396.0,337.0,16135.0,18709.0,325.0,-747.0,-313.0,12.0,24644.0,29576.0,550.0,23767.0,29371.0,524.0,877.0,205.0,26.0,21,3,41,3.0,1.0,0.0,0.0,1.0,0.6954,0.0,1.0,1.0,2.0,0.0,1.0,0.0,1.0,1.0,59305,1963.7417,2320.5298,1880.0000,137,4.5364,53,1.7550,51,297.0,9.8344,58837,38977,1290.6291,51785.0,802.0,197,118,20,33.0795

In [60]:
condensed_team_df = copy.copy(blue_teams_df)
for i in range(len(new_cols)):
    aux = new_cols[i].tolist()
    name = opp + new_col_names[i]
    condensed_team_df[name] = aux

In [61]:
condensed_team_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5730 entries, 10 to 69706
Columns: 115 entries, gameid to opp_cspm
dtypes: float64(87), int64(26), object(2)
memory usage: 5.1+ MB

In [62]:
condensed_team_df.head()

,gameid,side,gamelength,result,kills,deaths,assists,doublekills,triplekills,quadrakills,pentakills,firstblood,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,elders,opp_elders,firstherald,heralds,opp_heralds,firstbaron,barons,opp_barons,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,inhibitors,opp_inhibitors,damagetochampions,dpm,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,goldspent,gspd,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,opp_kills,opp_deaths,opp_assists,opp_doublekills,opp_triplekills,opp_quadrakills,opp_pentakills,opp_firstblood,opp_team_kpm,opp_infernals,opp_mountains,opp_clouds,opp_oceans,opp_firstherald,opp_firstbaron,opp_firsttower,opp_firstmidtower,opp_firsttothreetowers,opp_damagetochampions,opp_dpm,opp_damagetakenperminute,opp_damagemitigatedperminute,opp_wardsplaced,opp_wpm,opp_wardskilled,opp_wcpm,opp_controlwardsbought,opp_visionscore,opp_vspm,opp_totalgold,opp_earnedgold,opp_earned_gpm,opp_goldspent,opp_minionkills,opp_monsterkills,opp_monsterkillsownjungle,opp_monsterkillsenemyjungle,opp_cspm
10,ESPORTSTMNT03/1241318,Blue,2220,1,17,11,33,3.0,-1.0,-1.0,-1.0,-1.0,0.4595,0.7568,-1.0,2.0,3.0,2.0,3.0,-1.0,2.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,8.0,4.0,-1.0,-1.0,1.0,-1.0,77679,2099.4324,1975.3243,2302.4595,191,5.1622,97,2.6216,67,380.0,10.2703,68927,44905,1213.6486,62275.0,0.004023,1049.0,216,166,-1,34.1892,14615.0,17845.0,330.0,14498.0,17982.0,322.0,117.0,-137.0,8.0,21953.0,27219.0,507.0,22778.0,28884.0,519.0,-825.0,-1665.0,-12.0,11,17,25,0.0,0.0,0.0,0.0,1.0,0.2973,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,48685,1315.8108,2934.9459,3135.6486,172,4.6486,91,2.4595,69,318.0,8.5946,62709,38687,1045.5946,62025.0,1021.0,271,193,5,34.9189
22,ESPORTSTMNT03/1241322,Blue,2227,-1,5,21,16,1.0,-1.0,-1.0,-1.0,-1.0,0.1347,0.7005,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,2.0,-1.0,-1.0,2.0,-1.0,2.0,9.0,1.0,-1.0,-1.0,1.0,72963,1965.7746,2324.1042,2729.5016,144,3.8797,95,2.5595,58,254.0,6.8433,57283,33190,894.2075,56575.0,-0.122771,1011.0,183,151,1,32.1688,14180.0,16947.0,300.0,16194.0,19096.0,334.0,-2014.0,-2149.0,-34.0,21714.0,26869.0,501.0,27198.0,31702.0,557.0,-5484.0,-4833.0,-56.0,21,5,41,2.0,0.0,0.0,0.0,1.0,0.5658,0.0,1.0,1.0,2.0,1.0,1.0,1.0,0.0,1.0,65542,1765.8374,2861.2214,3192.7167,195,5.2537,90,2.4248,53,397.0,10.6960,72004,47911,1290.8217,63975.0,976.0,270,126,48,33.5698
34,ESPORTSTMNT03/1241324,Blue,1711,1,21,4,34,4.0,1.0,1.0,-1.0,-1.0,0.7364,0.8767,1.0,4.0,-1.0,4.0,-1.0,-1.0,2.0,1.0,1.0,-1.0,-1.0,1.0,2.0,-1.0,1.0,1.0,-1.0,1.0,10.0,1.0,1.0,1.0,2.0,-1.0,50728,1778.8895,2032.8112,2500.4676,111,3.8925,49,1.7183,42,262.0,9.1876,58078,39248,1376.3179,50660.0,0.225957,806.0,242,126,42,36.7504,15531.0,19034.0,365.0,14849.0,18419.0,340.0,682.0,615.0,25.0,24882.0,30349.0,584.0,22316.0,28252.0,531.0,2566.0,2097.0,53.0,4,21,11,1.0,0.0,0.0,0.0,1.0,0.1403,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,29684,1040.9351,2298.7259,2011.3150,96,3.3665,48,1.6832,49,194.0,6.8030,42465,23635,828.8136,40375.0,748.0,136,107,0,30.9994
46,ESPORTSTMNT03/1241328,Blue,1999,-1,4,17,8,-1.0,-1.0,-1.0,-1.0,-1.0,0.1201,0.6303,1.0,2.0,3.0,2.0,3.0,-1.0,1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,1.0,-1.0,-1.0,2.0,-1.0,3.0,9.0,-1.0,-1.0,-1.0,1.0,35364,1061.4507,2155.9180,2295.1876,143,4.2921,57,1.7109,51,248.0,7.4437,50749,28981,869.8649,48400.0,-0.170132,813.0,206,150,12,30.5853,14313.0,16950.0,308.0,15892.0,17808.0,329.0,-1579.0,-858.0,-21.0,22329.0,26093.0,465.0,24800.0,29157.0,535.0,-2471.0,-3064.0,-70.0,17,4,33,3.0,1.0,1.0,1.0,1.0,0.5103,0.0,0.0,3.0,0.0,0.0,1.0,1.0,1.0,1.0,54828,1645.6628,1772.5963,2063.5918,141,4.2321,81,2.4312,65,345.0,10.3552,64845,43077,1292.9565,57400.0,911.0,238,148,26,34.4872
58,ESPORTSTMNT03/1241386,Blue,1812,-1,3,21,7,-1.0,-1.0,-1.0,-1.0,-1.0,0.0993,0.7947,-1.0,1.0,4.0,1.0,4.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,1.0,1.0,-1.0,-1.0,-1.0,2.0,1.0,4.0,8.0,-1.0,-1.0,-1.0,1.0,42830,1418.2119,2763.4768,2432.5828,106,3.5099,56,1.8543,49,196.0,6.4901,48633,28773,952.7483,47010.0,-0.096665,799.0,205,151,7,33.2450,15388.0,18396.0,337.0,16135.0,18709.0,325.0,-747.0,-313.0,12.0,24644.0,29576.0,550.0,23767.0,29371.0,524.0,877.0,205.0,26.0,21,3,41,3.0,1.0,0.0,0.0,1.0,0.6954,0.0,1.0,1.0,2.0,0.0,1.0,0.0,1.0,1.0,59305,1963.7417,2320.5298,1880.0000,137,4.5364,53,1.7550,51,297.0,9.8344,58837,38977,1290.6291,51785.0,802.0,197,118,20,33.0795

##### No olvidar eliminar el atributo "side"

In [ ]:
#team_stats_df_no_na.drop("side", inplace = True, axis = 1)
#player_stats_df_no_na.drop("side", inplace = True, axis = 1)

In [63]:
condensed_team_df.drop("side", inplace = True, axis = 1)

##### Comentar con marisol sobre realizar prediccion solo con DF de equipos finalizado para posteriormente comparar el impacto de la informacion individual de cada jugador despues de condensar toda la informacion de jugadores junto con la informacion de equipos y sus resultados de prediccion

### EXPORTAR EL DATAFRAME PARA NO TENER QUE VOLVER A EJECUTAR TODO

In [66]:
condensed_team_df.to_csv('out.csv', index=False)

# BREAK LINE: A PARTIR DE AQUI SOLO MANIPULO OUT.CSV 
# SI NECESITO MOVER COSAS ANTES DE CREAR EL CSV TENGO QUE EJECUTAR TODO DESDE EL INICIO

In [40]:
team_df_na = pd.read_csv("out.csv")

In [41]:
team_df_na.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5730 entries, 0 to 5729
Columns: 114 entries, gameid to opp_cspm
dtypes: float64(87), int64(26), object(1)
memory usage: 5.0+ MB

In [42]:
a = team_df_na.isna().sum()

In [43]:
for i in range(len(a)):
    if a[i]>0:
        print(a[i], "index: ", i)

4 index:  0
1 index:  13
146 index:  27
1636 index:  53
1636 index:  57
146 index:  90
1636 index:  109
1636 index:  113

In [44]:
columnas_final = team_df_na.columns

In [45]:
columnas_final[0], columnas_final[13],columnas_final[27], columnas_final[53], columnas_final[57], columnas_final[90], columnas_final[109], columnas_final[113]

('gameid',
 'firstdragon',
 'firstbaron',
 'minionkills',
 'cspm',
 'opp_firstbaron',
 'opp_minionkills',
 'opp_cspm')

In [46]:
for i in range(len(team_df_na)):
    total_na = 0
    if team_df_na.iloc[i].isna().any():
        total_na += 1
print(total_na)

0

In [47]:
nulls = team_df_na.isnull()
row_null = nulls.any(axis=1)
rows_null = nulls[row_null]

In [48]:
rows_null

,gameid,gamelength,result,kills,deaths,assists,doublekills,triplekills,quadrakills,pentakills,...,opp_vspm,opp_totalgold,opp_earnedgold,opp_earned_gpm,opp_goldspent,opp_minionkills,opp_monsterkills,opp_monsterkillsownjungle,opp_monsterkillsenemyjungle,opp_cspm
10,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
11,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
12,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
13,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
14,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5489,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
5490,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
5523,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
5525,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
5526,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True

In [49]:
len(rows_null)

1637

In [50]:
rows_null.index[0]

10

In [51]:
type(team_df_na.index[0])

int

### para continuar con el trabajo decidi hacer drop de todas las entradas con elementos faltantes

In [52]:
#import copy
#prueba = copy.copy(team_df_na)

In [53]:
for i in range(len(rows_null)):
    ind = rows_null.index[i]
    team_df_na.drop(ind, inplace = True)

In [54]:
team_df_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4093 entries, 0 to 5729
Columns: 114 entries, gameid to opp_cspm
dtypes: float64(87), int64(26), object(1)
memory usage: 3.6+ MB

In [55]:
team_df_na.isna().sum()

gameid                         0
gamelength                     0
result                         0
kills                          0
deaths                         0
                              ..
opp_minionkills                0
opp_monsterkills               0
opp_monsterkillsownjungle      0
opp_monsterkillsenemyjungle    0
opp_cspm                       0
Length: 114, dtype: int64

# ESTE CSV ES EL BUENO DE EQUIPOS, NO TIENE NA, USALO

In [56]:
team_df_na.to_csv('team_df.csv', index=False)

# BREAK LINE, A PARTIR DE AQUI VOY A OPERAR CON EL DF DE JUGADORES

In [66]:
team_df_final = pd.read_csv("team_df.csv")

In [82]:
player_stats_df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 57300 entries, 0 to 69705
Data columns (total 56 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   gameid                    57260 non-null  object
 1   side                      57300 non-null  object
 2   position                  57300 non-null  object
 3   gamelength                57300 non-null  int64
 4   result                    57300 non-null  int64
 5   kills                     57300 non-null  int64
 6   deaths                    57300 non-null  int64
 7   assists                   57300 non-null  int64
 8   teamkills                 57300 non-null  int64
 9   teamdeaths                57300 non-null  int64
 10  doublekills               57300 non-null  float64
 11  triplekills               57300 non-null  float64
 12  quadrakills               57300 non-null  float64
 13  pentakills                57300 non-null  float64
 14  firstbloodkill            57300 non-null  float64
 15  damagetochampions         57300 non-null  int64
 16  dpm                       57300 non-null  float64
 17  damageshare               57300 non-null  float64
 18  damagetakenperminute      57300 non-null  float64
 19  damagemitigatedperminute  57300 non-null  float64
 20  wardsplaced               57300 non-null  int64
 21  wpm                       57300 non-null  float64
 22  wardskilled               57300 non-null  int64
 23  wcpm                      57300 non-null  float64
 24  controlwardsbought        57300 non-null  int64
 25  visionscore               57300 non-null  float64
 26  vspm                      57300 non-null  float64
 27  totalgold                 57300 non-null  int64
 28  earnedgold                57300 non-null  int64
 29  earned gpm                57300 non-null  float64
 30  earnedgoldshare           57300 non-null  float64
 31  goldspent                 57300 non-null  float64
 32  total cs                  57300 non-null  float64
 33  minionkills               57300 non-null  float64
 34  monsterkills              57300 non-null  int64
 35  monsterkillsownjungle     57300 non-null  int64
 36  monsterkillsenemyjungle   57300 non-null  int64
 37  cspm                      57300 non-null  float64
 38  goldat10                  57300 non-null  float64
 39  xpat10                    57300 non-null  float64
 40  csat10                    57300 non-null  float64
 41  opp_goldat10              57300 non-null  float64
 42  opp_xpat10                57300 non-null  float64
 43  opp_csat10                57300 non-null  float64
 44  golddiffat10              57300 non-null  float64
 45  xpdiffat10                57300 non-null  float64
 46  csdiffat10                57300 non-null  float64
 47  goldat15                  57300 non-null  float64
 48  xpat15                    57300 non-null  float64
 49  csat15                    57300 non-null  float64
 50  opp_goldat15              57300 non-null  float64
 51  opp_xpat15                57300 non-null  float64
 52  opp_csat15                57300 non-null  float64
 53  golddiffat15              57300 non-null  float64
 54  xpdiffat15                57300 non-null  float64
 55  csdiffat15                57300 non-null  float64
dtypes: float64(37), int64(16), object(3)
memory usage: 24.9+ MB

In [83]:
player_stats_df_no_na.head()

,gameid,side,position,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstbloodkill,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15
0,ESPORTSTMNT03/1241318,Blue,top,2220,1,0,3,7,17,11,0.0,0.0,0.0,0.0,0.0,15431,417.0541,0.198651,464.6216,488.2162,23,0.6216,3,0.0811,10,35.0,0.9459,13302,8498,229.6757,0.189235,11350.0,285.0,276.0,9,5,0,7.7027,3348.0,4864.0,88.0,2845.0,4432.0,65.0,503.0,432.0,23.0,4888.0,7368.0,131.0,4723.0,7202.0,118.0,165.0,166.0,13.0
1,ESPORTSTMNT03/1241318,Blue,jng,2220,1,4,0,9,17,11,1.0,0.0,0.0,0.0,0.0,11294,305.2432,0.145393,541.0541,289.1351,47,1.2703,26,0.7027,17,102.0,2.7568,13484,8680,234.5946,0.193288,12175.0,210.0,40.0,170,130,0,5.6757,2895.0,2887.0,57.0,3093.0,3010.0,67.0,-198.0,-123.0,-10.0,4385.0,4817.0,91.0,4784.0,4667.0,98.0,-399.0,150.0,-7.0
2,ESPORTSTMNT03/1241318,Blue,mid,2220,1,5,2,5,17,11,0.0,0.0,0.0,0.0,0.0,17396,470.1622,0.223947,372.4865,243.2162,39,1.0541,32,0.8649,7,99.0,2.6757,15419,10615,286.8919,0.236379,14225.0,320.0,312.0,8,2,0,8.6486,3110.0,4153.0,80.0,3261.0,4861.0,89.0,-151.0,-708.0,-9.0,4809.0,6275.0,129.0,5218.0,8112.0,140.0,-409.0,-1837.0,-11.0
3,ESPORTSTMNT03/1241318,Blue,bot,2220,1,7,1,9,17,11,2.0,0.0,0.0,0.0,0.0,29418,795.0811,0.378712,245.6216,657.4595,20,0.5405,30,0.8108,8,66.0,1.7838,18883,14079,380.5135,0.313520,16500.0,420.0,391.0,29,29,0,11.3514,3297.0,3233.0,93.0,3300.0,3250.0,90.0,-3.0,-17.0,3.0,4915.0,4959.0,136.0,4864.0,5360.0,135.0,51.0,-401.0,1.0
4,ESPORTSTMNT03/1241318,Blue,sup,2220,1,1,5,3,17,11,0.0,0.0,0.0,0.0,0.0,4140,111.8919,0.053296,351.5405,624.4324,62,1.6757,6,0.1622,25,78.0,2.1081,7839,3035,82.0270,0.067578,8025.0,30.0,30.0,0,0,0,0.8108,1965.0,2708.0,12.0,1999.0,2429.0,11.0,-34.0,279.0,1.0,2956.0,3800.0,20.0,3189.0,3543.0,28.0,-233.0,257.0,-8.0

##### columnas a eliminar:
- side
- result
- teamkills
- teamdeaths
- gamelength

##### columnas a renombrar con el prefijo "blue_":
-

##### columnas a replicar con el prefijo "red_":
-

In [86]:
type(team_df_final.columns)

pandas.core.indexes.base.Index

In [89]:
X = [team_df_final[team_df_final.columns]]

In [90]:
X

[                     gameid  gamelength  result  kills  deaths  assists  \
 0     ESPORTSTMNT03/1241318        2220       1     17      11       33
 1     ESPORTSTMNT03/1241322        2227      -1      5      21       16
 2     ESPORTSTMNT03/1241324        1711       1     21       4       34
 3     ESPORTSTMNT03/1241328        1999      -1      4      17        8
 4     ESPORTSTMNT03/1241386        1812      -1      3      21        7
 ...                     ...         ...     ...    ...     ...      ...
 4088  ESPORTSTMNT03/1532371        1801      -1      8      23       17
 4089  ESPORTSTMNT03/1532374        2323      -1      3       8        7
 4090  ESPORTSTMNT03/1552288        2294       1      9       3       17
 4091  ESPORTSTMNT03/1552298        2174      -1      7      12       18
 4092  ESPORTSTMNT03/1552301        1548      -1      7      21        8

       doublekills  triplekills  quadrakills  pentakills  firstblood  team kpm  \
 0             3.0         -1.0         -1.0        -1.0        -1.0    0.4595
 1             1.0         -1.0         -1.0        -1.0        -1.0    0.1347
 2             4.0          1.0          1.0        -1.0        -1.0    0.7364
 3            -1.0         -1.0         -1.0        -1.0        -1.0    0.1201
 4            -1.0         -1.0         -1.0        -1.0        -1.0    0.0993
 ...           ...          ...          ...         ...         ...       ...
 4088         -1.0         -1.0         -1.0        -1.0        -1.0    0.2665
 4089         -1.0         -1.0         -1.0        -1.0        -1.0    0.0775
 4090          1.0         -1.0         -1.0        -1.0         1.0    0.2354
 4091          1.0         -1.0         -1.0        -1.0         1.0    0.1932
 4092         -1.0         -1.0         -1.0        -1.0         1.0    0.2713

         ckpm  firstdragon  dragons  opp_dragons  elementaldrakes  \
 0     0.7568         -1.0      2.0          3.0              2.0
 1     0.7005         -1.0      1.0          4.0              1.0
 2     0.8767          1.0      4.0         -1.0              4.0
 3     0.6303          1.0      2.0          3.0              2.0
 4     0.7947         -1.0      1.0          4.0              1.0
 ...      ...          ...      ...          ...              ...
 4088  1.0328         -1.0      1.0          3.0              1.0
 4089  0.2841         -1.0      2.0          4.0              2.0
 4090  0.3139          1.0      5.0          1.0              4.0
 4091  0.5244         -1.0      2.0          3.0              2.0
 4092  1.0853         -1.0      2.0          2.0              2.0

       opp_elementaldrakes  infernals  mountains  clouds  oceans  elders  \
 0                     3.0       -1.0        2.0    -1.0    -1.0    -1.0
 1                     4.0       -1.0       -1.0    -1.0     1.0    -1.0
 2                    -1.0       -1.0        2.0     1.0     1.0    -1.0
 3                     3.0       -1.0        1.0    -1.0     1.0    -1.0
 4                     4.0       -1.0       -1.0    -1.0     1.0    -1.0
 ...                   ...        ...        ...     ...     ...     ...
 4088                  3.0       -1.0        1.0    -1.0    -1.0    -1.0
 4089                  4.0       -1.0        1.0     1.0    -1.0    -1.0
 4090                  1.0        2.0       -1.0     1.0     1.0     1.0
 4091                  3.0        1.0       -1.0    -1.0     1.0    -1.0
 4092                  2.0        1.0       -1.0    -1.0     1.0    -1.0

       opp_elders  firstherald  heralds  opp_heralds  firstbaron  barons  \
 0           -1.0          1.0      1.0          1.0         1.0     1.0
 1           -1.0         -1.0     -1.0          2.0        -1.0    -1.0
 2           -1.0          1.0      2.0         -1.0         1.0     1.0
 3           -1.0          1.0      1.0          1.0        -1.0    -1.0
 4           -1.0          1.0      1.0         -1.0        -1.0    -1.0
 ...          ...          ...      ...          ...         ...     ...
 4088        -1.0          1.0      1.0          1.0        -1.0    -1.0
 4089        -1.0          1.0      2.0         -1.0        -1.0    -1.0
 4090        -1.0          1.0      2.0         -1.0         1.0     2.0
 4091        -1.0          1.0      1.0          1.0        -1.0    -1.0
 4092        -1.0         -1.0      1.0          1.0        -1.0    -1.0

       opp_barons  firsttower  towers  opp_towers  firstmidtower  \
 0           -1.0        -1.0     8.0         4.0           -1.0
 1            2.0        -1.0     2.0         9.0            1.0
 2           -1.0         1.0    10.0         1.0            1.0
 3            2.0        -1.0     3.0         9.0           -1.0
 4            2.0         1.0     4.0         8.0           -1.0
 ...          ...         ...     ...         ...            ...
 4088         1.0        -1.0     1.0         9.0           -1.0
 4089         2.0         1.0     4.0         8.0            1.0
 4090        -1.0         1.0    11.0         2.0            1.0
 4091         1.0         1.0     3.0         9.0           -1.0
 4092         1.0         1.0     2.0         7.0            1.0

       firsttothreetowers  inhibitors  opp_inhibitors  damagetochampions  \
 0                   -1.0         1.0            -1.0              77679
 1                   -1.0        -1.0             1.0              72963
 2                    1.0         2.0            -1.0              50728
 3                   -1.0        -1.0             1.0              35364
 4                   -1.0        -1.0             1.0              42830
 ...                  ...         ...             ...                ...
 4088                -1.0        -1.0             1.0              49287
 4089                 1.0        -1.0             1.0              51193
 4090                 1.0         3.0            -1.0              58520
 4091                -1.0        -1.0             1.0              60948
 4092                -1.0        -1.0             1.0              55436

             dpm  damagetakenperminute  damagemitigatedperminute  wardsplaced  \
 0     2099.4324             1975.3243                 2302.4595          191
 1     1965.7746             2324.1042                 2729.5016          144
 2     1778.8895             2032.8112                 2500.4676          111
 3     1061.4507             2155.9180                 2295.1876          143
 4     1418.2119             2763.4768                 2432.5828          106
 ...         ...                   ...                       ...          ...
 4088  1641.9878             2495.7801                 2410.7940          103
 4089  1322.2471             3117.1330                 3828.1705          158
 4090  1530.6016             2096.6521                 1751.5083          143
 4091  1682.0975             2770.7360                 2945.5750          160
 4092  2148.6822             3372.7907                 2191.8605           84

          wpm  wardskilled    wcpm  controlwardsbought  visionscore     vspm  \
 0     5.1622           97  2.6216                  67        380.0  10.2703
 1     3.8797           95  2.5595                  58        254.0   6.8433
 2     3.8925           49  1.7183                  42        262.0   9.1876
 3     4.2921           57  1.7109                  51        248.0   7.4437
 4     3.5099           56  1.8543                  49        196.0   6.4901
 ...      ...          ...     ...                 ...          ...      ...
 4088  3.4314           39  1.2993                  25        189.0   6.2965
 4089  4.0809           53  1.3689                  47        304.0   7.8519
 4090  3.7402           75  1.9616                  58        349.0   9.1282
 4091  4.4158           53  1.4627                  58        289.0   7.9761
 4092  3.2558           41  1.5891                  35        172.0   6.6667

       totalgold  earnedgold  earned gpm  goldspent      gspd  minionkills  \
 0         68927       44905   1213.6486    62275.0  0.004023       1049.0
 1         57283       33190    894.2075    56575.0 -0.122771       1011.0
 2         58078       39248   1376.3179    50660.0  0.225957        806.0
 3         50749       28981    869.8649    48400.0 -0.170132        813.0
 4         48633       28773    952.7483    47010.0 -0.096665        799.0
 ...         ...         ...         ...        ...       ...          ...
 4088      44168       24420    813.5480    42600.0 -0.194437        662.0
 4089      63209       38136    985.0022    62185.0  0.036182       1086.0
 4090      72454       47677   1247.0009    65275.0  0.131394       1062.0
 4091      59844       36291   1001.5915    59308.0 -0.072507        967.0
 4092      40427       23259    901.5116    38585.0 -0.146845        673.0

       monsterkills  monsterkillsownjungle  monsterkillsenemyjungle     cspm  \
 0              216                    166                       -1  34.1892
 1              183                    151                        1  32.1688
 2              242                    126                       42  36.7504
 3              206                    150                       12  30.5853
 4              205                    151                        7  33.2450
 ...            ...                    ...                      ...      ...
 4088           148                    122                       -1  26.9850
 4089           268                    172                       23  34.9720
 4090           332                    204                       43  36.4603
 4091           248                    174                       13  33.5327
 4092           150                    102                        8  31.8992

       goldat10   xpat10  csat10  opp_goldat10  opp_xpat10  opp_csat10  \
 0      14615.0  17845.0   330.0       14498.0     17982.0       322.0
 1      14180.0  16947.0   300.0       16194.0     19096.0       334.0
 2      15531.0  19034.0   365.0       14849.0     18419.0       340.0
 3      14313.0  16950.0   308.0       15892.0     17808.0       329.0
 4      15388.0  18396.0   337.0       16135.0     18709.0       325.0
 ...        ...      ...     ...           ...         ...         ...
 4088   13711.0  16549.0   257.0       17768.0     19502.0       330.0
 4089   15390.0  19771.0   365.0       15261.0     18953.0       353.0
 4090   16101.0  19058.0   353.0       14928.0     17121.0       336.0
 4091   14654.0  17066.0   302.0       15608.0     18495.0       328.0
 4092   15884.0  19135.0   340.0       15630.0     18768.0       343.0

       golddiffat10  xpdiffat10  csdiffat10  goldat15   xpat15  csat15  \
 0            117.0      -137.0         8.0   21953.0  27219.0   507.0
 1          -2014.0     -2149.0       -34.0   21714.0  26869.0   501.0
 2            682.0       615.0        25.0   24882.0  30349.0   584.0
 3          -1579.0      -858.0       -21.0   22329.0  26093.0   465.0
 4           -747.0      -313.0        12.0   24644.0  29576.0   550.0
 ...            ...         ...         ...       ...      ...     ...
 4088       -4057.0     -2953.0       -73.0   23154.0  27813.0   406.0
 4089         129.0       818.0        12.0   24416.0  30879.0   566.0
 4090        1173.0      1937.0        17.0   24289.0  30410.0   573.0
 4091        -954.0     -1429.0       -26.0   24244.0  28529.0   518.0
 4092         254.0       367.0        -3.0   25045.0  30259.0   528.0

       opp_goldat15  opp_xpat15  opp_csat15  golddiffat15  xpdiffat15  \
 0          22778.0     28884.0       519.0        -825.0     -1665.0
 1          27198.0     31702.0       557.0       -5484.0     -4833.0
 2          22316.0     28252.0       531.0        2566.0      2097.0
 3          24800.0     29157.0       535.0       -2471.0     -3064.0
 4          23767.0     29371.0       524.0         877.0       205.0
 ...            ...         ...         ...           ...         ...
 4088       28818.0     31606.0       510.0       -5664.0     -3793.0
 4089       23336.0     30537.0       561.0        1080.0       342.0
 4090       23735.0     29784.0       560.0         554.0       626.0
 4091       25125.0     29449.0       547.0        -881.0      -920.0
 4092       23970.0     29715.0       543.0        1075.0       544.0

       csdiffat15  opp_kills  opp_deaths  opp_assists  opp_doublekills  \
 0          -12.0         11          17           25              0.0
 1          -56.0         21           5           41              2.0
 2           53.0          4          21           11              1.0
 3          -70.0         17           4           33              3.0
 4           26.0         21           3           41              3.0
 ...          ...        ...         ...          ...              ...
 4088      -104.0         23           9           30              2.0
 4089         5.0          8           3           22              1.0
 4090        13.0          3           9            5              0.0
 4091       -29.0         12           7           35              2.0
 4092       -15.0         21           7           34              1.0

       opp_triplekills  opp_quadrakills  opp_pentakills  opp_firstblood  \
 0                 0.0              0.0             0.0             1.0
 1                 0.0              0.0             0.0             1.0
 2                 0.0              0.0             0.0             1.0
 3                 1.0              1.0             1.0             1.0
 4                 1.0              0.0             0.0             1.0
 ...               ...              ...             ...             ...
 4088              1.0              1.0             0.0             1.0
 4089              0.0              0.0             0.0             1.0
 4090              0.0              0.0             0.0             0.0
 4091              0.0              0.0             0.0             0.0
 4092              0.0              0.0             0.0             0.0

       opp_team_kpm  opp_infernals  opp_mountains  opp_clouds  opp_oceans  \
 0           0.2973            1.0            1.0         1.0         0.0
 1           0.5658            0.0            1.0         1.0         2.0
 2           0.1403            0.0            0.0         0.0         0.0
 3           0.5103            0.0            0.0         3.0         0.0
 4           0.6954            0.0            1.0         1.0         2.0
 ...            ...            ...            ...         ...         ...
 4088        0.7662            2.0            0.0         0.0         1.0
 4089        0.2066            1.0            3.0         0.0         0.0
 4090        0.0785            1.0            0.0         0.0         0.0
 4091        0.3312            0.0            1.0         0.0         2.0
 4092        0.8140            1.0            1.0         0.0         0.0

       opp_firstherald  opp_firstbaron  opp_firsttower  opp_firstmidtower  \
 0                 0.0             0.0             1.0                1.0
 1                 1.0             1.0             1.0                0.0
 2                 0.0             0.0             0.0                0.0
 3                 0.0             1.0             1.0                1.0
 4                 0.0             1.0             0.0                1.0
 ...               ...             ...             ...                ...
 4088              0.0             1.0             1.0                1.0
 4089              0.0             1.0             0.0                0.0
 4090              0.0             0.0             0.0                0.0
 4091              0.0             1.0             0.0                1.0
 4092              1.0             1.0             0.0                0.0

       opp_firsttothreetowers  opp_damagetochampions    opp_dpm  \
 0                        1.0                  48685  1315.8108
 1                        1.0                  65542  1765.8374
 2                        0.0                  29684  1040.9351
 3                        1.0                  54828  1645.6628
 4                        1.0                  59305  1963.7417
 ...                      ...                    ...        ...
 4088                     1.0                  57154  1904.0755
 4089                     0.0                  91447  2361.9544
 4090                     0.0                  49173  1286.1290
 4091                     1.0                  66171  1826.2466
 4092                     1.0                  72742  2819.4574

       opp_damagetakenperminute  opp_damagemitigatedperminute  opp_wardsplaced  \
 0                    2934.9459                     3135.6486              172
 1                    2861.2214                     3192.7167              195
 2                    2298.7259                     2011.3150               96
 3                    1772.5963                     2063.5918              141
 4                    2320.5298                     1880.0000              137
 ...                        ...                           ...              ...
 4088                 2929.1061                     1625.2304               90
 4089                 2027.3698                     2065.3638              110
 4090                 2231.4821                     1585.2921              152
 4091                 2414.4618                     2744.4618              124
 4092                 3224.3411                     2341.5891               96

       opp_wpm  opp_wardskilled  opp_wcpm  opp_controlwardsbought  \
 0      4.6486               91    2.4595                      69
 1      5.2537               90    2.4248                      53
 2      3.3665               48    1.6832                      49
 3      4.2321               81    2.4312                      65
 4      4.5364               53    1.7550                      51
 ...       ...              ...       ...                     ...
 4088   2.9983               42    1.3992                      35
 4089   2.8412               87    2.2471                      52
 4090   3.9756               66    1.7262                      61
 4091   3.4223               72    1.9871                      51
 4092   3.7209               40    1.5504                      35

       opp_visionscore  opp_vspm  opp_totalgold  opp_earnedgold  \
 0               318.0    8.5946          62709           38687
 1               397.0   10.6960          72004           47911
 2               194.0    6.8030          42465           23635
 3               345.0   10.3552          64845           43077
 4               297.0    9.8344          58837           38977
 ...               ...       ...            ...             ...
 4088            200.0    6.6630          59293           39545
 4089            303.0    7.8261          70016           44943
 4090            316.0    8.2650          60149           35372
 4091            290.0    8.0037          67931           44378
 4092            204.0    7.9070          51370           34202

       opp_earned_gpm  opp_goldspent  opp_minionkills  opp_monsterkills  \
 0          1045.5946        62025.0           1021.0               271
 1          1290.8217        63975.0            976.0               270
 2           828.8136        40375.0            748.0               136
 3          1292.9565        57400.0            911.0               238
 4          1290.6291        51785.0            802.0               197
 ...              ...            ...              ...               ...
 4088       1317.4348        51775.0            692.0               233
 4089       1160.8179        59975.0           1108.0               286
 4090        925.1613        57227.0           1085.0               233
 4091       1224.7838        63770.0           1003.0               284
 4092       1325.6589        44700.0            676.0               202
